# Generated by Django 4.1.6 on 2023-03-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoLS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewbook',
            name='category',
            field=models.CharField(choices=[('text', 'Textbook'), ('research', 'Research Book'), ('literary', 'Literary Book')], max_length=10),
        ),
    ]
