# Generated by Django 4.1.5 on 2023-04-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoLS', '0002_alter_viewbook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewteachingload',
            name='load_even',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='viewteachingload',
            name='load_odd',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='viewteachingload',
            name='load_tri',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
