emails = [
    "Suresh.Kumar@spm.pdpu.ac.in",
    "Avnish.Jadav@spt.pdpu.ac.in",
    "Sandeep.Pathak@spm.pdpu.ac.in",
    "shankar.yadav@spt.pdpu.ac.in",
    "Hiral.Vyas@spm.pdpu.ac.in",
    "Bharat.Chaudhari@spm.pdpu.ac.in",
    "ajay.verma@spm.pdpu.ac.in",
    "Rutvi.Marfatiya@spt.pdpu.ac.in",
    "dinesh.chaudhari@spt.pdpu.ac.in",
    "Nilesh.Thaker@spt.pdpu.ac.in",
    "Somdutt.Sharma@spm.pdpu.ac.in",
    "remya.rajan@pdpu.ac.in",
    "Sunil.Prajapati@spt.pdpu.ac.in",
    "Vasudev.Trivedi@spt.pdpu.ac.in",
    "Sanjay.Prajapati@spt.pdpu.ac.in",
    "Ashok.Chavda@spt.pdpu.ac.in",
    "jitendra.patel@sot.pdpu.ac.in",
    "Uttam.Rahevar@sot.pdpu.ac.in",
    "Bhavesh.Mehta@spt.pdpu.ac.in",
    "Pinakin.Goswami@spt.pdpu.ac.in",
    "Kalpesh.Yagnik@spt.pdpu.ac.in",
    "Snehal.Bhavsar@pdpu.ac.in",
    "Yatin.Patel@sot.pdpu.ac.in",
    "Jayesh.Panchal@sot.pdpu.ac.in",
    "Anil.Patel@sot.pdpu.ac.in",
    "rohit.mishra@pdpu.ac.in",
    "Patel.Shailesh@sot.pdpu.ac.in",
    "Mehul.Bhalu@sot.pdpu.ac.in",
    "hemang.upadhyay@pdpu.ac.in",
    "Kinjal.Mehta@pdpu.ac.in",
    "Aashutosh.Patel@spt.pdpu.ac.in",
    "Suvik.Patel@spt.pdpu.ac.in",
    "Hiral.Prajapati@pdpu.ac.in",
    "Jitendra.Rupala@pdpu.ac.in",
    "Abhilash.Nair@pdpu.ac.in",
    "Punyata.Bhagat@sot.pdpu.ac.in",
    "piyush.chaudhary@sot.pdpu.ac.in",
    "dhaval.santola@sot.pdpu.ac.in",
    "Bhavesh.P@spt.pdpu.ac.in",
    "Kunal.Lalwani@pdpu.ac.in",
    "Jitendra.Prajapati@sot.pdpu.ac.in",
    "Manali.Shah@pdpu.ac.in",
    "Arvind.Makwana@sot.pdpu.ac.in",
    "Alpesh.Rajput@sot.pdpu.ac.in",
    "Prashant.Patel@sot.pdpu.ac.in",
    "Shashi.Tiwari@pdpu.ac.in",
    "Vineet.Bagaria@pdpu.ac.in",
    "Suruchi.Patel@spt.pdpu.ac.in",
    "bhashin.mehta@spt.pdpu.ac.in",
    "Chirag.Pandya@spt.pdpu.ac.in",
    "Nirav.Upadhyay@sls.pdpu.ac.in",
    "Ankit.Panchal@pdpu.ac.in",
    "Rohit.Makhija@pdpu.ac.in",
    "trushar.prajapati@sot.pdpu.ac.in",
    "Hetal.Vasani@sls.pdpu.ac.in",
    "vijay.suthar@sot.pdpu.ac.in",
    "Shanti.Chaudhari@sls.pdpu.ac.in",
    "Jvalant.Oza@sot.pdpu.ac.in",
    "sachin.mishra@pdpu.ac.in",
    "Mohit.Goyal@pdpu.ac.in",
    "Jignesh.Rami@pdpu.ac.in",
    "Vandan.soni@sot.pdpu.ac.in",
    "sachin.patel@sot.pdpu.ac.in",
    "Nilesh.Pande@sot.pdpu.ac.in",
    "Hitendra.patel@spt.pdpu.ac.in",
    "Umang.Soni@sot.pdpu.ac.in",
    "dhrumil.patel@spt.pdpu.ac.in",
    "Dushyant.Dave@sls.pdpu.ac.in",
    "Hasmukh.Khatri@sse.pdpu.ac.in",
    "Bhavin.Chhatrala@pdpu.ac.in",
    "Harikrushna.Patel@pdpu.ac.in",
    "fulesh.desai@spt.pdpu.ac.in",
    "Ravindra.sadhu@spt.pdpu.ac.in",
    "Shailesh.patel@spt.pdpu.ac.in",
    "Martin.Santhan@pdpu.ac.in",
    "Shailja.Tripathi@sot.pdpu.ac.in",
    "Mittal.Shah@sot.pdpu.ac.in",
    "Dharmendra.Gadhavi@spt.pdpu.ac.in",
    "Richi.mehta@pdpu.ac.in",
    "Sandhya.pillai@pdpu.ac.in",
    "Shailesh.Sakariya@sot.pdpu.ac.in",
    "Purvi.Upadhyay@pdpu.ac.in",
    "Rajendra.Thakor@sls.pdpu.ac.in",
    "Vijay.Hariyani@spt.pdpu.ac.in",
    "Pavan.Prajapati@pdpu.ac.in",
    "Bhaunesh.Shah@pdpu.ac.in",
    "Ronak.Gopani@sls.pdpu.ac.in",
    "Hiren.Solanki@sls.pdpu.ac.in",
    "Mithilesh.Dave@pdpu.ac.in",
    "Vikrant.Vala@pdpu.ac.in",
    "Vishal.Bhatt@pdpu.ac.in",
    "Ashwini.Raisinghani@sls.pdpu.ac.in",
    "amit.koshti@pdpu.ac.in",
    "jaimini.parmar@sot.pdpu.ac.in",
    "Nadeem.Gandharva@pdpu.ac.in",
    "Sandhya.Sonkusare@iic.pdpu.ac.in",
    "Ketan.Anand@sot.pdpu.ac.in",
    "Bhavinkumar.Patel@spt.pdpu.ac.in",
    "jay.prajapati@spt.pdpu.ac.in",
    "Nikunj.Parekh@spt.pdpu.ac.in",
    "Irshad.Gandharva@spt.pdpu.ac.in",
    "Panthi.Ganatra@sot.pdpu.ac.in",
    "Radhika.Thaker@pdpu.ac.in",
    "Sonal.Mishra@pdpu.ac.in",
    "Krupali.Gohel@pdpu.ac.in",
    "Dhvani.Vyas@pdpu.ac.in",
    "savan.prajapati@sot.pdpu.ac.in",
    "Arti.Mishra@sot.pdpu.ac.in",
    "Abhinaya.R@pdpu.ac.in",
    "Parita.Bhavsar@sls.pdpu.ac.in",
    "Harshad.Purani@sot.pdpu.ac.in",
    "Nikita.Patel@sot.pdpu.ac.in",
    "Krupesh.Prajapati@sot.pdpu.ac.in",
    "Daxa.Chaudhari@sot.pdpu.ac.in",
    "Manasi.Raval@sot.pdpu.ac.in",
    "mohit.gamit@pdpu.ac.in",
    "urvi.bhati@pdpu.ac.in",
    "Bhargav.Chhatrala@sls.pdpu.ac.in",
    "Ruchi.Bhatt@spt.pdpu.ac.in",
    "Vishal.Asnani@sot.pdpu.ac.in",
    "Rashmi.thakur@sot.pdpu.ac.in",
    "Akash.Panchal@sot.pdpu.ac.in",
    "Brijrajsinh.Vaghela@sot.pdpu.ac.in",
    "Nirav.Chavda@sot.pdpu.ac.in",
    "Apeksha.Brahmbhatt@sot.pdpu.ac.in",
    "Rohit.Chauhan@spt.pdpu.ac.in",
    "Payal.Patel@spt.pdpu.ac.in",
    "Nitin.Rathod@sot.pdpu.ac.in",
    "Mukesh.Kushwah@pdpu.ac.in",
    "Rinkal.Kyada@sot.pdpu.ac.in",
    "Krina.P@sot.pdpu.ac.in",
    "Jitendra.Paghadal@sot.pdpu.ac.in",
    "Hasmukh.P@spt.pdpu.ac.in",
    "SanketB.Patel@sot.pdpu.ac.in",
    "Rahul.Koshti@spt.pdpu.ac.in",
    "Sunil.Singh@pdpu.ac.in",
    "Khushboo.Yadav@spt.pdpu.ac.in",
    "UmangR.Patel@spt.pdpu.ac.in",
    "Vishal.Panchal@spt.pdpu.ac.in",
]


def reverse_staff_r2():
    from Staff.models import StaffAppraisalFile, StaffValidation
    from django.db import transaction

    with transaction.atomic():
        for email in emails:
            file = StaffAppraisalFile.objects.get(user__email=email)
            file.ro2_grading_done = False
            file.file_level = 'RO2'
            file.ro2_validation = StaffValidation()
            file.ro2_validation.save()
            file.save()

reverse_staff_r2()

