# Generated by Django 4.1.6 on 2023-02-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.FileField(upload_to='bulkupload/templates')),
            ],
            options={
                'verbose_name': 'Download Template',
                'verbose_name_plural': 'Download Template',
            },
        ),
        migrations.CreateModel(
            name='UploadCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(blank=True, choices=[('1', 'Upload CSV')], max_length=100, null=True)),
                ('file', models.FileField(upload_to='csv_files')),
            ],
            options={
                'verbose_name': 'Upload CSV',
                'verbose_name_plural': 'Upload CSV',
            },
        ),
    ]
