# Generated by Django 4.1.6 on 2023-02-10 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BulkUploadFoET.uploadcsv')),
            ],
        ),
    ]
