# Generated by Django 4.1.6 on 2023-02-11 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BulkUploadFoET', '0002_verifyuploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyuploaded',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uploadcsv',
            name='upload_type',
            field=models.CharField(choices=[('academia_collab', 'Academia Collaboration'), ('co_curricular', 'Co-Curricular Activities'), ('consultancy', 'Providing Consultancy'), ('patent', 'Patent'), ('phd_guidance', 'PhD Guidance'), ('project', 'Project'), ('scopus_wos', 'Paper Publications in Scopus and Web os Science'), ('books', 'Books and Publications'), ('exam_duty', 'Exam Duty'), ('student_feedback', 'Student Feedback'), ('teaching_load', 'Teaching Load')], max_length=100),
        ),
        migrations.CreateModel(
            name='ViewAcademiaCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academia_collab_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
