# Generated by Django 4.1.6 on 2023-02-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0003_verifyuploaded_clear_alter_uploadcsv_upload_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verifyuploaded',
            name='clear',
        ),
    ]
