# Generated by Django 4.1.6 on 2023-02-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0004_remove_verifyuploaded_clear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifyuploaded',
            name='csv_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='BulkUploadFoET.uploadcsv'),
        ),
    ]
