# Generated by Django 4.1.6 on 2023-02-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0006_alter_verifyuploaded_csv_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewacademiacollaboration',
            name='csv_origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academia_collab_bulk_csv', to='BulkUploadFoET.uploadcsv'),
            preserve_default=False,
        ),
    ]
