# Generated by Django 4.1.6 on 2023-02-11 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BulkUploadFoET', '0008_delete_template_remove_verifyuploaded_csv_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.FileField(upload_to='bulkupload/templates')),
            ],
            options={
                'verbose_name': 'Download Template',
                'verbose_name_plural': 'Download Template',
            },
        ),
        migrations.CreateModel(
            name='UploadCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('academia_collab', 'Academia Collaboration'), ('co_curricular', 'Co-Curricular Activities'), ('consultancy', 'Providing Consultancy'), ('patent', 'Patent'), ('phd_guidance', 'PhD Guidance'), ('project', 'Project'), ('scopus_wos', 'Paper Publications in Scopus and Web os Science'), ('books', 'Books and Publications'), ('exam_duty', 'Exam Duty'), ('student_feedback', 'Student Feedback'), ('teaching_load', 'Teaching Load')], max_length=100)),
                ('file', models.FileField(upload_to='csv_files')),
            ],
            options={
                'verbose_name': 'Upload CSV',
                'verbose_name_plural': 'Upload CSV',
            },
        ),
        migrations.CreateModel(
            name='ViewAcademiaCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academia_collab_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academia_collab_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerifyUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BulkUploadFoET.uploadcsv')),
            ],
        ),
    ]
