# Generated by Django 4.1.6 on 2023-02-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
        migrations.RemoveField(
            model_name='verifyuploaded',
            name='csv_origin',
        ),
        migrations.RemoveField(
            model_name='viewacademiacollaboration',
            name='csv_origin',
        ),
        migrations.RemoveField(
            model_name='viewacademiacollaboration',
            name='faculty',
        ),
        migrations.DeleteModel(
            name='UploadCSV',
        ),
        migrations.DeleteModel(
            name='VerifyUploaded',
        ),
        migrations.DeleteModel(
            name='ViewAcademiaCollaboration',
        ),
    ]
