# Generated by Django 4.1.6 on 2023-02-11 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BulkUploadFoET', '0011_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadcsv',
            options={},
        ),
        migrations.CreateModel(
            name='ViewTeachingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('load_odd', models.IntegerField()),
                ('load_even', models.IntegerField()),
                ('load_tri', models.IntegerField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_load_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_load_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewStudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('student_feedback', models.FloatField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewScopusWos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('entity_name', models.TextField()),
                ('paper_quality', models.CharField(max_length=5)),
                ('isbn', models.CharField(max_length=100)),
                ('conference_organization', models.CharField(max_length=100)),
                ('conference_level', models.CharField(max_length=100)),
                ('is_main_author', models.BooleanField(default=False)),
                ('co_author_count', models.IntegerField()),
                ('is_scopus', models.BooleanField(default=False)),
                ('is_wos', models.BooleanField(default=False)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopus_wos_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopus_wos_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('funding_agency', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('role', models.CharField(choices=[('pi', 'PI'), ('copi', 'CO-PI')], max_length=4)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('is_institutional', models.BooleanField(default=False)),
                ('is_osrp', models.BooleanField(default=False)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewPhDGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phd_guidance_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phd_guidance_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewPatent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('application_no', models.CharField(max_length=100)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewExamDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('timely_investigation', models.FloatField()),
                ('paper_setting', models.FloatField()),
                ('evaluation', models.FloatField()),
                ('result_submission', models.FloatField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_duty_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_duty_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('marks', models.FloatField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultancy_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewCoCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_curricular_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_curricular_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('level', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('is_main_author', models.BooleanField(default=False)),
                ('co_author_count', models.IntegerField()),
                ('is_editor', models.BooleanField(default=False)),
                ('isbn', models.CharField(max_length=100)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
