# Generated by Django 4.1.6 on 2023-02-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0012_alter_uploadcsv_options_viewteachingload_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadcsv',
            options={'ordering': ['id'], 'verbose_name': 'Upload CSV', 'verbose_name_plural': 'Upload CSV'},
        ),
        migrations.RemoveField(
            model_name='viewconsultancy',
            name='marks',
        ),
    ]
