# Generated by Django 4.1.6 on 2023-02-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0013_alter_uploadcsv_options_remove_viewconsultancy_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewteachingload',
            name='load_tri',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
