# Generated by Django 4.1.6 on 2023-02-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0014_alter_viewteachingload_load_tri'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verifyuploaded',
            options={'verbose_name': 'Verify Uploaded', 'verbose_name_plural': 'Verify Uploaded'},
        ),
        migrations.AlterModelOptions(
            name='viewacademiacollaboration',
            options={'verbose_name': 'View Academia Collaboration', 'verbose_name_plural': 'View Academia Collaboration'},
        ),
        migrations.AlterModelOptions(
            name='viewbook',
            options={'verbose_name': 'View Book', 'verbose_name_plural': 'View Books'},
        ),
        migrations.AlterModelOptions(
            name='viewcocurricular',
            options={'verbose_name': 'View Co-Curricular & Extra-Curricular Activities', 'verbose_name_plural': 'View Co-Curricular & Extra-Curricular Activities'},
        ),
        migrations.AlterModelOptions(
            name='viewconsultancy',
            options={'verbose_name': 'View Consultancy Provided', 'verbose_name_plural': 'View Consultancies Provided'},
        ),
        migrations.AlterModelOptions(
            name='viewexamduty',
            options={'verbose_name': 'View Exam Duty', 'verbose_name_plural': 'View Exam Duties'},
        ),
        migrations.AlterModelOptions(
            name='viewpatent',
            options={'verbose_name': 'View Patent', 'verbose_name_plural': 'View Patents'},
        ),
        migrations.AlterModelOptions(
            name='viewphdguidance',
            options={'verbose_name': 'View PhD Guidance', 'verbose_name_plural': 'View PhD Guidance'},
        ),
        migrations.AlterModelOptions(
            name='viewproject',
            options={'verbose_name': 'View Project', 'verbose_name_plural': 'View Projects'},
        ),
        migrations.AlterModelOptions(
            name='viewscopuswos',
            options={'verbose_name': 'View Publication in Scopus/WOS', 'verbose_name_plural': 'View Publications in Scopus/WOS'},
        ),
        migrations.AlterModelOptions(
            name='viewstudentfeedback',
            options={'verbose_name': 'View Student Feedback', 'verbose_name_plural': 'View Student Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='viewteachingload',
            options={'verbose_name': 'View Teaching Load', 'verbose_name_plural': 'View Teaching Loads'},
        ),
    ]
