# Generated by Django 4.1.6 on 2023-02-11 21:31

import BulkUpload.BulkUploadFoET.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BulkUploadFoET', '0015_alter_verifyuploaded_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error', models.TextField()),
                ('type', models.CharField(choices=[('validation', 'Validation'), ('deletion', 'Deletion')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=BulkUpload.BulkUploadFoET.models.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='error_log_user', to=settings.AUTH_USER_MODEL)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_log_csv', to='BulkUploadFoET.uploadcsv')),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
            },
        ),
    ]
