# Generated by Django 4.1.6 on 2023-02-11 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BulkUploadFoET', '0016_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='error_log_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
