# Generated by Django 4.1.6 on 2023-02-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0017_alter_errorlog_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='csv_origin',
            field=models.CharField(max_length=100),
        ),
    ]
