# Generated by Django 4.1.6 on 2023-02-11 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0018_alter_errorlog_csv_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='upload_type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='csv_origin',
            field=models.URLField(),
        ),
    ]
