# Generated by Django 4.1.6 on 2023-02-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0019_errorlog_upload_type_alter_errorlog_csv_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlog',
            name='csv_origin',
            field=models.FileField(blank=True, null=True, upload_to='error_logs'),
        ),
    ]
