# Generated by Django 4.1.6 on 2023-02-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0021_alter_errorlog_upload_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorLog',
        ),
    ]
