# Generated by Django 4.1.6 on 2023-02-11 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BulkUploadFoET', '0022_delete_errorlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_origin', models.FileField(blank=True, null=True, upload_to='error_logs')),
                ('upload_type', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.TextField()),
                ('type', models.CharField(choices=[('validation', 'Validation'), ('deletion', 'Deletion')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='error_log_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
            },
        ),
    ]
