# Generated by Django 4.1.6 on 2023-02-18 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BulkUploadFoET', '0023_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='upload_type',
            field=models.CharField(choices=[('academia_collab', 'Academia Collaboration'), ('co_curricular', 'Co-Curricular Activities'), ('award', 'Awards'), ('consultancy', 'Providing Consultancy'), ('patent', 'Patent'), ('phd_guidance', 'PhD Guidance'), ('project', 'Project'), ('scopus_wos', 'Paper Publications in Scopus and Web os Science'), ('books', 'Books and Publications'), ('exam_duty', 'Exam Duty'), ('student_feedback', 'Student Feedback'), ('teaching_load', 'Teaching Load')], max_length=100),
        ),
        migrations.CreateModel(
            name='ViewAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2023)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_bulk_csv', to='BulkUploadFoET.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Award',
                'verbose_name_plural': 'View Awards',
            },
        ),
    ]
