# Generated by Django 4.1.6 on 2023-02-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0024_alter_uploadcsv_upload_type_viewaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewaward',
            name='level',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
