# Generated by Django 4.1.6 on 2023-02-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0025_viewaward_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewexamduty',
            old_name='timely_investigation',
            new_name='timely_invigilation',
        ),
    ]
