# Generated by Django 4.1.6 on 2023-02-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0026_rename_timely_investigation_viewexamduty_timely_invigilation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewbook',
            name='category',
            field=models.CharField(choices=[('text', 'Textbook'), ('research', 'Research Book')], max_length=10),
        ),
    ]
