# Generated by Django 4.1.6 on 2023-02-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0027_alter_viewbook_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewproject',
            name='is_institutional_marks',
            field=models.FloatField(default=0),
        ),
    ]
