# Generated by Django 4.1.6 on 2023-02-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0028_viewproject_is_institutional_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewacademiacollaboration',
            name='mou_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='viewacademiacollaboration',
            name='mou_marks',
            field=models.FloatField(default=0),
        ),
    ]
