# Generated by Django 4.1.6 on 2023-02-20 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0029_viewacademiacollaboration_mou_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewproject',
            old_name='is_institutional_marks',
            new_name='institutional_marks',
        ),
    ]
