# Generated by Django 4.1.6 on 2023-03-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0031_alter_uploadcsv_upload_type_viewadditionalmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadcsv',
            name='upload_type',
            field=models.CharField(choices=[('academia_collab', 'Academia Collaboration'), ('co_curricular', 'Co-Curricular Activities'), ('award', 'Awards'), ('consultancy', 'Providing Consultancy'), ('patent', 'Patent'), ('phd_guidance', 'PhD Guidance'), ('project', 'Project'), ('scopus_wos', 'Paper Publications in Scopus and Web of Science'), ('books', 'Books and Publications'), ('exam_duty', 'Exam Duty'), ('student_feedback', 'Student Feedback'), ('teaching_load', 'Teaching Load'), ('additional', 'Additional Marks (Placement & Admission')], max_length=100),
        ),
    ]
