# Generated by Django 4.1.5 on 2023-05-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulkUploadFoET', '0033_alter_viewteachingload_load_even_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewscopuswos',
            name='conference_organization',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='viewscopuswos',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
