# Generated by Django 4.1.6 on 2023-03-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyMaths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathgoalsheetassistantprofoncontract',
            options={'verbose_name': 'Goalsheet Configuration for Maths Assistant Professor On Contract', 'verbose_name_plural': 'Goalsheet Configurations for Maths Assistant Professor On Contract'},
        ),
    ]
