# Generated by Django 4.1.6 on 2023-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyMaths', '0004_alter_markfield_ro1_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathassistantprofappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mathassistantprofappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mathassistantprofappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mathassistantprofoncontractappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mathassistantprofoncontractappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mathassistantprofoncontractappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mathassociateprofappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mathassociateprofappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mathassociateprofappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mathprofappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mathprofappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='mathprofappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
    ]
