# Generated by Django 4.1.6 on 2023-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyMaths', '0005_mathassistantprofappraisalfile_additional_responsibilities_grade_r2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathassistantprofappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mathassociateprofappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mathprofappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=False),
        ),
    ]
