# Generated by Django 4.1.6 on 2023-04-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyMaths', '0006_alter_mathassistantprofappraisalfile_industry_collaboration_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathassistantprofappraisalfile',
            name='is_assistant_prof_on_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mathassociateprofappraisalfile',
            name='is_assistant_prof_on_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mathprofappraisalfile',
            name='is_assistant_prof_on_contract',
            field=models.BooleanField(default=False),
        ),
    ]
