# Generated by Django 4.1.5 on 2023-05-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyMaths', '0007_mathassistantprofappraisalfile_is_assistant_prof_on_contract_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mathgoalsheetassistantprof',
            old_name='section_1e_iii_per_international_book_per_author',
            new_name='section_1e_ii_per_international_book_per_author',
        ),
        migrations.RenameField(
            model_name='mathgoalsheetassistantprof',
            old_name='section_1e_iii_per_national_book_per_author',
            new_name='section_1e_ii_per_national_book_per_author',
        ),
        migrations.RemoveField(
            model_name='mathgoalsheetassistantprof',
            name='section_1e_ii_per_book_per_author',
        ),
        migrations.RemoveField(
            model_name='mathgoalsheetassistantprof',
            name='section_1e_iii_per_chapter',
        ),
        migrations.AlterField(
            model_name='mathgoalsheetassistantprof',
            name='section_1e_ii_per_chapter',
            field=models.IntegerField(default=5),
        ),
    ]
