from .assistant_prof_on_contract import ScienceGoalSheetAssistantProfOnContract
from .assistant_prof import ScienceGoalSheetAssistantProf
from .associate_prof import ScienceGoalSheetAssociateProf
from .prof import ScienceGoalSheetProf