# Generated by Django 4.1.6 on 2023-02-05 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacultyFOET', '0002_alter_foetgoalsheetprof_evaluation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ro1', models.FloatField(default=0)),
                ('ro2', models.FloatField(default=0)),
                ('final', models.FloatField(default=0)),
                ('ro1_remarks', models.TextField(blank=True, null=True)),
                ('ro2_remarks', models.TextField(blank=True, null=True)),
                ('final_remarks', models.TextField(blank=True, null=True)),
                ('ro2_agrees_with_ro1', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('award_type', models.CharField(blank=True, choices=[('regional', 'Regional'), ('state', 'State'), ('national', 'National'), ('international', 'International')], max_length=100, null=True, verbose_name='Award Type')),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('awardee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
    ]
