# Generated by Django 4.1.6 on 2023-02-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0003_markfield_award'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_type',
            field=models.CharField(blank=True, choices=[('regional', 'Regional'), ('state', 'State'), ('national', 'National'), ('international', 'International')], max_length=100, null=True),
        ),
    ]
