# Generated by Django 4.1.6 on 2023-02-05 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacultyFOET', '0004_alter_award_award_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration_category', models.CharField(auto_created=True, blank=True, choices=[('project', 'Project'), ('consultancy', 'Consultancy')], max_length=100, null=True)),
                ('collaboration_type', models.CharField(auto_created=True, blank=True, choices=[('academia_collab', 'Academia Collaboration'), ('collab', 'Collaboration'), ('consultancy_edp_mdp', 'Consultancy, EDP, MDP'), ('sci_collab', 'Scientific Collaboration')], max_length=100, null=True)),
                ('year', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('collaborator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
    ]
