# Generated by Django 4.1.6 on 2023-02-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0005_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='month',
            field=models.IntegerField(default=0),
        ),
    ]
