# Generated by Django 4.1.6 on 2023-02-06 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacultyFOET', '0006_collaboration_amount_collaboration_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='award_type',
            field=models.CharField(blank=True, choices=[('university', 'University'), ('regional', 'Regional'), ('state', 'State'), ('national', 'National'), ('international', 'International')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('book', 'Book'), ('book_chapter', 'Book Chapter'), ('edited_book', 'Edited Book'), ('edited_book_chapter', 'Edited Book Chapter')], max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('research', 'Research'), ('textbook', 'Textbook')], max_length=50, null=True)),
                ('publication_level', models.CharField(blank=True, choices=[('national', 'National'), ('international', 'International')], max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=0)),
                ('project_category', models.CharField(blank=True, choices=[('A', 'Above 1 Crore'), ('B', 'Above 70 Lakhs'), ('C', 'Above 50 Lakhs'), ('D', 'Above 30 Lakhs'), ('E', 'Above 15 Lakhs'), ('F', 'Above 5 Lakhs'), ('G', 'Above 3 Lakhs'), ('H', 'Above 50 Thousand'), ('INS', 'Institutional'), ('OSRP', 'OSRP Student Research Project')], max_length=100, null=True)),
                ('project_participation', models.CharField(blank=True, choices=[('pi', 'Principal Investigator'), ('co_pi', 'Co-Principal Investigator')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('funding_agency', models.CharField(blank=True, max_length=200, null=True)),
                ('funds_received', models.FloatField(default=0)),
                ('status', models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=100, null=True)),
                ('innovator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.CreateModel(
            name='PhDGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('awarded', 'Awarded'), ('synopsis', 'Synopsis Submitted'), ('ongoing', 'Under Progress')], max_length=100, null=True)),
                ('innovator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=0)),
                ('patent_type', models.CharField(blank=True, choices=[('filed', 'Filed'), ('published', 'Published'), ('granted', 'Granted'), ('licensed', 'Granted & Licensed'), ('advisor', 'Advisor')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('innovator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=0)),
                ('paper_type', models.CharField(blank=True, choices=[('journal', 'Journal'), ('conference', 'Conference')], max_length=100, null=True)),
                ('author_type', models.CharField(blank=True, choices=[('main', 'Main Author'), ('co', 'Co-Author')], max_length=100, null=True)),
                ('co_author_count', models.IntegerField(default=0)),
                ('quality', models.CharField(blank=True, choices=[('q1', 'Q1'), ('q2', 'Q2'), ('q3', 'Q3'), ('q4', 'Q4')], max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('scopus', 'Scopus'), ('wos', 'Web of Science'), ('other', 'Other')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=100, null=True)),
                ('conference_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.CreateModel(
            name='MastersDissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('submitted_patent_published', 'Submitted and Patent Published'), ('submitted_patent_granted', 'Submitted and Patent Granted'), ('submitted_patent_papers_published', 'Submitted and Patent Granted/Published Papers Published')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.CreateModel(
            name='BachelorsDissertation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=0)),
                ('is_awarded', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('students', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
    ]
