# Generated by Django 4.1.6 on 2023-02-08 10:20

import Staff.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacultyFOET', '0007_alter_award_award_type_alter_award_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markfield',
            name='ro1_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='markfield',
            name='ro2_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GenericMarkedParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('appraisee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_mooc', models.BooleanField(default=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=Staff.models.user_directory_path)),
                ('grade', models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=100, null=True)),
                ('appraisee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.CreateModel(
            name='AcademiaCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(default=0)),
                ('mou_signed', models.BooleanField(default=False)),
                ('faculty_contributed', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('appraisee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
    ]
