# Generated by Django 4.1.6 on 2023-02-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0009_foetassistantprofoncontractappraisalfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='grand_total',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grand_total', to='FacultyFOET.markfield'),
        ),
    ]
