# Generated by Django 4.1.6 on 2023-02-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0010_alter_foetassistantprofoncontractappraisalfile_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='configuration',
        ),
    ]
