# Generated by Django 4.1.6 on 2023-02-08 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0011_remove_foetassistantprofoncontractappraisalfile_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='configuration',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='FacultyFOET.foetgoalsheetassistantprofoncontract'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='is_mooc_available',
            field=models.BooleanField(default=False),
        ),
    ]
