# Generated by Django 4.1.6 on 2023-02-09 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0013_foetprofappraisalfile_foetassociateprofappraisalfile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phdguidance',
            old_name='innovator',
            new_name='faculty',
        ),
    ]
