# Generated by Django 4.1.6 on 2023-02-14 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacultyFOET', '0014_rename_innovator_phdguidance_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='has_verified_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
