# Generated by Django 4.1.6 on 2023-02-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0016_foetassistantprofappraisalfile_has_verified_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='academia_collaboration_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_academia_collaboration_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='arranging_conferences_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_arranging_conferences_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='attending_conferences_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_attending_conferences_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='bachelors_dissertation_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_bachelors_dissertation_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='being_mentor_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_being_mentor_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='books_and_publications_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_books_and_publications_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='community_development_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_community_development_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='evaluation_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_evaluation_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='exam_duty_total_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_exam_duty_total_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='grand_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_grand_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='industry_collaboration_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_industry_collaboration_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='involvement_extra_curricular_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_involvement_extra_curricular_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='masters_thesis_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_masters_thesis_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='modern_teaching_methods_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_modern_teaching_methods_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='mooc_courses_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_mooc_courses_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='paper_setting_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_paper_setting_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='part_a_section_1_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_part_a_section_1_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='part_a_section_2_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_part_a_section_2_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='part_a_section_2a_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_part_a_section_2a_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='part_a_section_2b_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_part_a_section_2b_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='part_a_section_3_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_part_a_section_3_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='part_a_section_4_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_part_a_section_4_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='part_a_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_part_a_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='part_b_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_part_b_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='patents_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_patents_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='providing_consultancy_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_providing_consultancy_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='recognition_awards_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_recognition_awards_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='result_submission_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_result_submission_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='self_development_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_self_development_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='student_feedback',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='student_feedback_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_student_feedback_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='teaching_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='teaching_load_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_teaching_load_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='timely_investigation_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_timely_investigation_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='academia_collaboration_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academia_collaboration_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='arranging_conferences_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arranging_conferences_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='attending_conferences_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attending_conferences_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='bachelors_dissertation_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bachelors_dissertation_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='being_mentor_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='being_mentor_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='books_and_publications_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_and_publications_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='community_development_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_development_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='evaluation_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='exam_duty_total_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_duty_total_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='faculty_advisor_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_advisor_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='grand_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grand_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='industry_collaboration_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industry_collaboration_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='involvement_extra_curricular_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='involvement_extra_curricular_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='masters_thesis_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='masters_thesis_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='modern_teaching_methods_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modern_teaching_methods_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='mooc_courses_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mooc_courses_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='paper_setting_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper_setting_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='part_a_section_1_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_a_section_1_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='part_a_section_2_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_a_section_2_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='part_a_section_2a_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_a_section_2a_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='part_a_section_2b_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_a_section_2b_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='part_a_section_3_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_a_section_3_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='part_a_section_4_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_a_section_4_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='part_a_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_a_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='part_b_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_b_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='patents_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patents_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='providing_consultancy_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providing_consultancy_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='recognition_awards_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recognition_awards_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='result_submission_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result_submission_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='self_development_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='self_development_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='student_feedback',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='student_feedback_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='teaching_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='teaching_load_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_load_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='timely_investigation_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timely_investigation_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='academia_collaboration_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_academia_collaboration_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='arranging_conferences_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_arranging_conferences_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='attending_conferences_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_attending_conferences_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='bachelors_dissertation_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_bachelors_dissertation_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='being_mentor_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_being_mentor_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='books_and_publications_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_books_and_publications_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='community_development_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_community_development_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='evaluation_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_evaluation_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='exam_duty_total_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_exam_duty_total_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='grand_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_grand_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='industry_collaboration_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_industry_collaboration_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='involvement_extra_curricular_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_involvement_extra_curricular_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='modern_teaching_methods_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_modern_teaching_methods_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='mooc_courses_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_mooc_courses_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='paper_setting_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_paper_setting_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='part_a_section_1_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_part_a_section_1_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='part_a_section_2_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_part_a_section_2_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='part_a_section_2a_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_part_a_section_2a_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='part_a_section_2b_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_part_a_section_2b_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='part_a_section_4_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_part_a_section_4_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='part_a_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_part_a_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='part_b_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_part_b_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='patents_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_patents_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='providing_consultancy_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_providing_consultancy_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='recognition_awards_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_recognition_awards_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='result_submission_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_result_submission_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='self_development_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_self_development_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='student_feedback',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='student_feedback_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_student_feedback_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='teaching_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='teaching_load_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_teaching_load_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='timely_investigation_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_timely_investigation_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='academia_collaboration_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_academia_collaboration_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='arranging_conferences_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_arranging_conferences_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='attending_conferences_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_attending_conferences_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='bachelors_dissertation_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_bachelors_dissertation_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='being_mentor_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_being_mentor_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='books_and_publications_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_books_and_publications_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='community_development_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_community_development_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='evaluation_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_evaluation_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='exam_duty_total_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_exam_duty_total_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='grand_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_grand_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='industry_collaboration_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_industry_collaboration_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='involvement_extra_curricular_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_involvement_extra_curricular_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='masters_thesis_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_masters_thesis_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='modern_teaching_methods_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_modern_teaching_methods_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='mooc_courses_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_mooc_courses_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='paper_setting_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_paper_setting_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='part_a_section_1_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_part_a_section_1_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='part_a_section_2_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_part_a_section_2_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='part_a_section_2a_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_part_a_section_2a_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='part_a_section_2b_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_part_a_section_2b_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='part_a_section_3_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_part_a_section_3_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='part_a_section_4_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_part_a_section_4_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='part_a_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_part_a_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='part_b_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_part_b_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='patents_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_patents_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='providing_consultancy_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_providing_consultancy_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='recognition_awards_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_recognition_awards_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='result_submission_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_result_submission_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='self_development_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_self_development_total', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='student_feedback',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='student_feedback_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_student_feedback_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='teaching_load',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='teaching_load_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_teaching_load_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='timely_investigation_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_timely_investigation_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
