# Generated by Django 4.1.6 on 2023-02-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0019_alter_foetassociateprofappraisalfile_part_a_section_3_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foetassistantprofappraisalfile',
            options={'verbose_name': 'FoET Assistant Professor Appraisal File', 'verbose_name_plural': 'FoET Assistant Professor Appraisal Files'},
        ),
        migrations.AlterModelOptions(
            name='foetassistantprofoncontractappraisalfile',
            options={'verbose_name': 'FoET Assistant Professor On Contract Appraisal File', 'verbose_name_plural': 'FoET Assistant Professor On Contract Appraisal Files'},
        ),
        migrations.AlterModelOptions(
            name='foetassociateprofappraisalfile',
            options={'verbose_name': 'FoET Associate Professor File', 'verbose_name_plural': 'FoET Associate Professor Files'},
        ),
        migrations.AlterModelOptions(
            name='foetprofappraisalfile',
            options={'verbose_name': 'FoET Professor File', 'verbose_name_plural': 'FoET Professor Files'},
        ),
    ]
