# Generated by Django 4.1.6 on 2023-02-18 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0020_alter_foetassistantprofappraisalfile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='collaboration_category',
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='count',
        ),
        migrations.RemoveField(
            model_name='markfield',
            name='final',
        ),
        migrations.RemoveField(
            model_name='markfield',
            name='final_remarks',
        ),
        migrations.AddField(
            model_name='award',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='collaboration_type',
            field=models.CharField(auto_created=True, blank=True, choices=[('consultancy_edp_mdp', 'Consultancy, EDP, MDP')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='type',
            field=models.CharField(blank=True, choices=[('book', 'Book'), ('book_chapter', 'Book Chapter'), ('edited_book_chapter', 'Edited Book Chapter')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ModernMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flip_classes', models.TextField(blank=True, null=True)),
                ('case_study', models.TextField(blank=True, null=True)),
                ('technology_integration', models.TextField(blank=True, null=True)),
                ('design_thinking', models.TextField(blank=True, null=True)),
                ('project_based_teaching', models.TextField(blank=True, null=True)),
                ('other', models.TextField(blank=True, null=True)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='modern_teaching_methods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modern_teaching_methods', to='FacultyFOET.modernmethods'),
        ),
    ]
