# Generated by Django 4.1.6 on 2023-02-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0021_rename_description_publication_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='author_type',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='conference_name',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='organization',
        ),
        migrations.AddField(
            model_name='paper',
            name='conference_level',
            field=models.CharField(blank=True, choices=[('national', 'National'), ('international', 'International')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='conference_organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='entity_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_main_author',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(blank=True, choices=[('journal', 'Journal'), ('conference', 'Conference'), ('epub', 'E-Publication'), ('article', 'Article')], max_length=100, null=True),
        ),
    ]
