# Generated by Django 4.1.6 on 2023-02-18 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FacultyFOET', '0022_rename_description_paper_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboration',
            old_name='collaborator',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='patent',
            old_name='description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='academiacollaboration',
            name='faculty_contributed',
        ),
        migrations.RemoveField(
            model_name='academiacollaboration',
            name='month',
        ),
        migrations.RemoveField(
            model_name='academiacollaboration',
            name='mou_signed',
        ),
        migrations.RemoveField(
            model_name='bachelorsdissertation',
            name='students',
        ),
        migrations.RemoveField(
            model_name='phdguidance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='phdguidance',
            name='month',
        ),
        migrations.AddField(
            model_name='bachelorsdissertation',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastersdissertation',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phdguidance',
            name='scopus_publications',
            field=models.IntegerField(blank=True, null=True, verbose_name='Scopus Publications (Only for External)'),
        ),
        migrations.AddField(
            model_name='phdguidance',
            name='student_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='academiacollaboration',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='award',
            name='award_type',
            field=models.CharField(blank=True, choices=[('international', 'International'), ('national', 'National'), ('state', 'State'), ('regional', 'Regional'), ('university', 'University')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='bachelorsdissertation',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='certification',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='collaboration_type',
            field=models.CharField(auto_created=True, blank=True, choices=[('industry', 'Industry Collaboration')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='collaboration',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='genericmarkedparameter',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='mastersdissertation',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='patent',
            name='patent_type',
            field=models.CharField(blank=True, choices=[('filed', 'Filed'), ('published', 'Published'), ('granted', 'Granted'), ('licensed', 'Granted & Licensed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='phdguidance',
            name='status',
            field=models.CharField(blank=True, choices=[('awarded', 'Awarded'), ('synopsis', 'Synopsis Submitted'), ('ongoing', 'Under Progress'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phdguidance',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='project',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.CreateModel(
            name='FacultyAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2023)),
                ('month', models.IntegerField(default=0)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultancy_type', models.CharField(auto_created=True, blank=True, choices=[('consultancy_edp_mdp', 'Consultancy, EDP, MDP')], max_length=100, null=True)),
                ('year', models.IntegerField(default=2023)),
                ('month', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.FloatField(default=0)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield')),
            ],
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='faculty_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
        migrations.DeleteModel(
            name='AdvisorActivity',
        ),
    ]
