# Generated by Django 4.1.6 on 2023-02-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0024_rename_involvement_extra_curricular_total_foetassistantprofoncontractappraisalfile_involvement_extra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foetassistantprofappraisalfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='foetassociateprofappraisalfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='foetprofappraisalfile',
            options={},
        ),
        migrations.RenameField(
            model_name='foetassistantprofappraisalfile',
            old_name='involvement_extra_curricular_total',
            new_name='involvement_extra_curricular_marks',
        ),
        migrations.RenameField(
            model_name='foetassociateprofappraisalfile',
            old_name='involvement_extra_curricular_total',
            new_name='involvement_extra_curricular_marks',
        ),
        migrations.RenameField(
            model_name='foetprofappraisalfile',
            old_name='involvement_extra_curricular_total',
            new_name='involvement_extra_curricular_marks',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='evaluation_marks',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='exam_duty_total_marks',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='involvement_extra_curricular',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='modern_teaching_methods_marks',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='paper_setting_marks',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='part_a_section_2b_total',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='result_submission_marks',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='teaching_load_marks',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='timely_investigation_marks',
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='evaluation_marks',
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='exam_duty_total_marks',
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='involvement_extra_curricular',
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='modern_teaching_methods_marks',
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='paper_setting_marks',
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='part_a_section_2b_total',
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='result_submission_marks',
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='teaching_load_marks',
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='timely_investigation_marks',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='evaluation_marks',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='exam_duty_total_marks',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='involvement_extra_curricular',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='modern_teaching_methods_marks',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='paper_setting_marks',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='part_a_section_2b_total',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='result_submission_marks',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='teaching_load_marks',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='timely_investigation_marks',
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='dissertation_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_dissertation_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='exam_duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_exam_duty_total_marks', to='FacultyFOET.examduty'),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='faculty_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='faculty_advisor_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_faculty_advisor_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='modern_teaching_methods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_modern_teaching_methods', to='FacultyFOET.modernmethods'),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='phd_guidance_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_phd_guidance_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='projects_total_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_projects_total_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='dissertation_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_dissertation_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='exam_duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_exam_duty_total_marks', to='FacultyFOET.examduty'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='faculty_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='faculty_advisor_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_faculty_advisor_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='modern_teaching_methods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_modern_teaching_methods', to='FacultyFOET.modernmethods'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='phd_guidance_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_phd_guidance_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='projects_total_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_projects_total_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='dissertation_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_dissertation_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='exam_duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_exam_duty_total_marks', to='FacultyFOET.examduty'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='faculty_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='faculty_advisor_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_faculty_advisor_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='modern_teaching_methods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_modern_teaching_methods', to='FacultyFOET.modernmethods'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='phd_guidance_total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_phd_guidance_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='projects_total_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_projects_total_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='e_publications_articles',
            field=models.ManyToManyField(blank=True, related_name='asst_prof_e_publications_articles', to='FacultyFOET.paper'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='industry_collaboration',
            field=models.ManyToManyField(blank=True, related_name='asst_prof_industry_collaboration', to='FacultyFOET.collaboration'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='providing_consultancy',
            field=models.ManyToManyField(blank=True, related_name='asst_prof_providing_consultancy', to='FacultyFOET.consultancy'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='teaching_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_teaching_load', to='FacultyFOET.teachingload'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='e_publications_articles',
            field=models.ManyToManyField(blank=True, related_name='assoc_prof_e_publications_articles', to='FacultyFOET.paper'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='industry_collaboration',
            field=models.ManyToManyField(blank=True, related_name='assoc_prof_industry_collaboration', to='FacultyFOET.collaboration'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='providing_consultancy',
            field=models.ManyToManyField(blank=True, related_name='assoc_prof_providing_consultancy', to='FacultyFOET.consultancy'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='teaching_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_teaching_load', to='FacultyFOET.teachingload'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='e_publications_articles',
            field=models.ManyToManyField(blank=True, related_name='prof_e_publications_articles', to='FacultyFOET.paper'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='industry_collaboration',
            field=models.ManyToManyField(blank=True, related_name='prof_industry_collaboration', to='FacultyFOET.collaboration'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='providing_consultancy',
            field=models.ManyToManyField(blank=True, related_name='prof_providing_consultancy', to='FacultyFOET.consultancy'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='teaching_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_teaching_load', to='FacultyFOET.teachingload'),
        ),
    ]
