# Generated by Django 4.1.6 on 2023-02-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0025_alter_foetassistantprofappraisalfile_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examduty',
            old_name='timely_investigation',
            new_name='timely_invigilation',
        ),
    ]
