# Generated by Django 4.1.6 on 2023-02-19 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0026_rename_timely_investigation_examduty_timely_invigilation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patent',
            old_name='patent_type',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_participation',
            field=models.CharField(blank=True, choices=[('pi', 'Principal Investigator'), ('copi', 'Co-Principal Investigator')], max_length=100, null=True),
        ),
    ]
