# Generated by Django 4.1.6 on 2023-02-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0027_rename_patent_type_patent_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='application_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
