# Generated by Django 4.1.6 on 2023-02-19 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0028_patent_application_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_validated', models.BooleanField(default=False)),
                ('phd_validated', models.BooleanField(default=False)),
                ('dissertation_validated', models.BooleanField(default=False)),
                ('patents_validated', models.BooleanField(default=False)),
                ('recognition_validated', models.BooleanField(default=False)),
                ('consultancy_validated', models.BooleanField(default=False)),
                ('arranging_conferences_validated', models.BooleanField(default=False)),
                ('mentorship_validated', models.BooleanField(default=False)),
                ('attending_conferences_validated', models.BooleanField(default=False)),
                ('community_development_validated', models.BooleanField(default=False)),
                ('additional_validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='consultancy_type',
            field=models.CharField(blank=True, choices=[('consultancy_edp_mdp', 'Consultancy, EDP, MDP')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_validator', to='FacultyFOET.facultyvalidator'),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_prof_on_contract_validator', to='FacultyFOET.facultyvalidator'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_validator', to='FacultyFOET.facultyvalidator'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_validator', to='FacultyFOET.facultyvalidator'),
        ),
    ]
