# Generated by Django 4.1.6 on 2023-02-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0029_facultyvalidator_alter_consultancy_consultancy_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='is_assistant_prof_on_contract',
            field=models.BooleanField(default=True),
        ),
    ]
