# Generated by Django 4.1.6 on 2023-02-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0030_foetassistantprofoncontractappraisalfile_is_assistant_prof_on_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='co_author_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publication',
            name='is_main_author',
            field=models.BooleanField(default=False),
        ),
    ]
