# Generated by Django 4.1.6 on 2023-02-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0031_publication_co_author_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phdguidance',
            name='category',
            field=models.CharField(blank=True, choices=[('internal', 'Internal'), ('external', 'External')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phdguidance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='phdguidance',
            name='student_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.CharField(blank=True, choices=[('research', 'Research Book'), ('textbook', 'Text Book')], max_length=50, null=True),
        ),
    ]
