# Generated by Django 4.1.6 on 2023-02-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0032_phdguidance_category_phdguidance_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='external_phd_guidance_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='external_phd_guidance_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='external_phd_guidance_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='external_phd_guidance_available',
            field=models.BooleanField(default=True),
        ),
    ]
