# Generated by Django 4.1.6 on 2023-02-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0033_foetassistantprofappraisalfile_external_phd_guidance_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='bachelors_dissertation_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='masters_thesis_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='bachelors_dissertation_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='masters_thesis_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='bachelors_dissertation_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='masters_thesis_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='bachelors_dissertation_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='masters_thesis_available',
            field=models.BooleanField(default=True),
        ),
    ]
