# Generated by Django 4.1.6 on 2023-02-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0034_foetassistantprofappraisalfile_bachelors_dissertation_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='faculty_advisor_available',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='faculty_advisor',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='faculty_advisor',
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='faculty_advisor',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='faculty_advisor',
        ),
        migrations.AlterField(
            model_name='mastersdissertation',
            name='status',
            field=models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('submitted_patent_published', 'Submitted and Patent Published / Granted'), ('submitted_patent_papers_published', 'Submitted and Patent Granted/Published Papers Published')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='faculty_advisor',
            field=models.ManyToManyField(blank=True, null=True, related_name='asst_prof_faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='faculty_advisor',
            field=models.ManyToManyField(blank=True, null=True, related_name='faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='faculty_advisor',
            field=models.ManyToManyField(blank=True, null=True, related_name='assoc_prof_faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='faculty_advisor',
            field=models.ManyToManyField(blank=True, null=True, related_name='prof_faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
    ]
