# Generated by Django 4.1.6 on 2023-02-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0035_foetassistantprofoncontractappraisalfile_faculty_advisor_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyvalidator',
            name='recognition_validated',
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='faculty_advisor',
            field=models.ManyToManyField(blank=True, related_name='asst_prof_faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='faculty_advisor',
            field=models.ManyToManyField(blank=True, related_name='faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='faculty_advisor',
            field=models.ManyToManyField(blank=True, related_name='assoc_prof_faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='faculty_advisor',
            field=models.ManyToManyField(blank=True, related_name='prof_faculty_advisor', to='FacultyFOET.facultyadvisor'),
        ),
    ]
