# Generated by Django 4.1.6 on 2023-02-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0036_remove_facultyvalidator_recognition_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='arranging_conferences_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='attending_conferences_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='being_mentor_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='community_development_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='arranging_conferences_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='attending_conferences_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='being_mentor_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='community_development_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='arranging_conferences_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='attending_conferences_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='being_mentor_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='community_development_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='arranging_conferences_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='attending_conferences_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='being_mentor_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='community_development_available',
            field=models.BooleanField(default=True),
        ),
    ]
