# Generated by Django 4.1.6 on 2023-02-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0037_foetassistantprofappraisalfile_arranging_conferences_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='genericmarkedparameter',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
