# Generated by Django 4.1.6 on 2023-02-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0038_foetassistantprofoncontractappraisalfile_industry_collaboration_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='grade',
        ),
        migrations.AddField(
            model_name='certification',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
