# Generated by Django 4.1.6 on 2023-02-19 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0039_remove_certification_grade_certification_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='mooc_courses',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='mooc_courses',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='mooc_courses',
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='mooc_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_mooc_course', to='FacultyFOET.certification'),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='mooc_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mooc_course', to='FacultyFOET.certification'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='mooc_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_mooc_course', to='FacultyFOET.certification'),
        ),
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='is_mooc_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='is_mooc_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='foetassociateprofappraisalfile',
            name='is_mooc_available',
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='mooc_courses',
        ),
        migrations.AlterField(
            model_name='foetprofappraisalfile',
            name='is_mooc_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='mooc_courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_mooc_courses', to='FacultyFOET.certification'),
        ),
    ]
