# Generated by Django 4.1.6 on 2023-02-19 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0040_remove_foetassistantprofappraisalfile_mooc_courses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foetassociateprofappraisalfile',
            old_name='mooc_courses',
            new_name='mooc_course',
        ),
    ]
