# Generated by Django 4.1.6 on 2023-02-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0041_rename_mooc_courses_foetassociateprofappraisalfile_mooc_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='appraisee',
            new_name='user',
        ),
    ]
