# Generated by Django 4.1.6 on 2023-02-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0042_rename_appraisee_certification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academiacollaboration',
            name='marks',
        ),
        migrations.AddField(
            model_name='academiacollaboration',
            name='contribution_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrib_marks', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='academiacollaboration',
            name='mou_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FacultyFOET.markfield'),
        ),
    ]
