# Generated by Django 4.1.6 on 2023-02-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0043_remove_academiacollaboration_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='file_level',
            field=models.CharField(choices=[('APPRAISEE', 'APPRAISEE'), ('RO1', 'Reporting Officer (RO)'), ('RO2', 'Reviewing Officer (RV)')], default='APPRAISEE', max_length=10),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='file_level',
            field=models.CharField(choices=[('APPRAISEE', 'APPRAISEE'), ('RO1', 'Reporting Officer (RO)'), ('RO2', 'Reviewing Officer (RV)')], default='APPRAISEE', max_length=10),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='file_level',
            field=models.CharField(choices=[('APPRAISEE', 'APPRAISEE'), ('RO1', 'Reporting Officer (RO)'), ('RO2', 'Reviewing Officer (RV)')], default='APPRAISEE', max_length=10),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='file_level',
            field=models.CharField(choices=[('APPRAISEE', 'APPRAISEE'), ('RO1', 'Reporting Officer (RO)'), ('RO2', 'Reviewing Officer (RV)')], default='APPRAISEE', max_length=10),
        ),
    ]
