# Generated by Django 4.1.6 on 2023-02-22 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0044_foetassistantprofappraisalfile_file_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foetassistantprofappraisalfile',
            name='academia_collaboration',
        ),
        migrations.RemoveField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='academia_collaboration',
        ),
        migrations.RemoveField(
            model_name='foetassociateprofappraisalfile',
            name='academia_collaboration',
        ),
        migrations.RemoveField(
            model_name='foetprofappraisalfile',
            name='academia_collaboration',
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='academia_collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_academia_collaboration', to='FacultyFOET.academiacollaboration'),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='academia_collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academia_collaboration', to='FacultyFOET.academiacollaboration'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='academia_collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_academia_collaboration', to='FacultyFOET.academiacollaboration'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='academia_collaboration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_academia_collaboration', to='FacultyFOET.academiacollaboration'),
        ),
    ]
