# Generated by Django 4.1.6 on 2023-03-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0045_remove_foetassistantprofappraisalfile_academia_collaboration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='ro1_validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_r1_validator', to='FacultyFOET.facultyvalidator'),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='ro2_validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_r2_validator', to='FacultyFOET.facultyvalidator'),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='ro1_validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_prof_on_contract_r1_validator', to='FacultyFOET.facultyvalidator'),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='ro2_validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_prof_on_contract_r2_validator', to='FacultyFOET.facultyvalidator'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='ro1_validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_r1_validator', to='FacultyFOET.facultyvalidator'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='ro2_validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_r2_validator', to='FacultyFOET.facultyvalidator'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='ro1_validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_r1_validator', to='FacultyFOET.facultyvalidator'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='ro2_validator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_r2_validator', to='FacultyFOET.facultyvalidator'),
        ),
    ]
