# Generated by Django 4.1.6 on 2023-03-13 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0046_foetassistantprofappraisalfile_ro1_validator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='admission_duty_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_admission_duty_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='placement_duty_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asst_prof_placement_duty_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='admission_duty_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_duty_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='placement_duty_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placement_duty_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='admission_duty_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_admission_duty_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='placement_duty_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assoc_prof_placement_duty_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='admission_duty_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_admission_duty_total', to='FacultyFOET.markfield'),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='placement_duty_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_placement_duty_total', to='FacultyFOET.markfield'),
        ),
    ]
