# Generated by Django 4.1.6 on 2023-03-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0047_foetassistantprofappraisalfile_admission_duty_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetgoalsheetassistantprof',
            name='section_2b_phd_guidance_external',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='foetgoalsheetassistantprof',
            name='section_2b_phd_guidance_external_max',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='foetgoalsheetassistantprofoncontract',
            name='section_2b_phd_guidance_external',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='foetgoalsheetassistantprofoncontract',
            name='section_2b_phd_guidance_external_max',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='foetgoalsheetassociateprof',
            name='section_2b_phd_guidance_external',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='foetgoalsheetassociateprof',
            name='section_2b_phd_guidance_external_max',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='foetgoalsheetprof',
            name='section_2b_phd_guidance_external',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='foetgoalsheetprof',
            name='section_2b_phd_guidance_external_max',
            field=models.IntegerField(default=2),
        ),
    ]
