# Generated by Django 4.1.6 on 2023-03-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0049_alter_foetassistantprofappraisalfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foetassistantprofappraisalfile',
            options={'verbose_name': 'FoET Assistant Professor Appraisal File', 'verbose_name_plural': 'FoET Assistant Professor Appraisal Files'},
        ),
    ]
