# Generated by Django 4.1.6 on 2023-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0051_alter_markfield_ro1_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
    ]
