# Generated by Django 4.1.6 on 2023-04-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0052_foetassistantprofappraisalfile_additional_responsibilities_grade_r2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyvalidator',
            name='academia_collab_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyvalidator',
            name='award_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyvalidator',
            name='extra_curricular_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyvalidator',
            name='project_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyvalidator',
            name='research_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyvalidator',
            name='senior_feedback_validated',
            field=models.BooleanField(default=False),
        ),
    ]
