# Generated by Django 4.1.6 on 2023-04-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0053_facultyvalidator_academia_collab_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foetassistantprofappraisalfile',
            name='file_level',
            field=models.CharField(choices=[('APPRAISEE', 'APPRAISEE'), ('RO1', 'Reporting Officer (RO)'), ('RO2', 'Reviewing Officer (RV)'), ('HR', 'Human Resources (HR)')], default='APPRAISEE', max_length=10),
        ),
    ]
