# Generated by Django 4.1.6 on 2023-04-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0055_alter_foetassistantprofoncontractappraisalfile_file_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='file_level',
            field=models.CharField(choices=[('APPRAISEE', 'APPRAISEE'), ('RO1', 'RO1'), ('RO2', 'RO2'), ('HR', 'HR')], default='APPRAISEE', max_length=10),
        ),
    ]
