# Generated by Django 4.1.6 on 2023-04-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0056_alter_foetassistantprofoncontractappraisalfile_file_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='file_level',
            field=models.CharField(choices=[('APPRAISEE', 'APPRAISEE'), ('RO1', 'Reporting Officer (RO)'), ('RO2', 'Reviewing Officer (RV)'), ('HR', 'HR')], default='APPRAISEE', max_length=10),
        ),
    ]
