# Generated by Django 4.1.6 on 2023-04-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0057_alter_foetassistantprofoncontractappraisalfile_file_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='is_assistant_prof_on_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='is_assistant_prof_on_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='is_assistant_prof_on_contract',
            field=models.BooleanField(default=False),
        ),
    ]
