# Generated by Django 4.1.6 on 2023-04-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0058_foetassistantprofappraisalfile_is_assistant_prof_on_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='faculty_advisor_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='faculty_advisor_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='faculty_advisor_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=False),
        ),
    ]
