# Generated by Django 4.1.5 on 2023-05-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyFOET', '0059_foetassistantprofappraisalfile_faculty_advisor_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='r1_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='r1_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='r2_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofappraisalfile',
            name='r2_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='r1_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='r1_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='r2_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foetassistantprofoncontractappraisalfile',
            name='r2_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='r1_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='r1_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='r2_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foetassociateprofappraisalfile',
            name='r2_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='r1_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='r1_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='r2_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='foetprofappraisalfile',
            name='r2_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
