"""
Django settings for APAS project.

Generated by 'django-admin startproject' using Django 4.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.getenv('DEBUG'))

ALLOWED_HOSTS = ['localhost', 'localhost:80', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['http://localhost:80', 'http://127.0.0.1']
for host in os.getenv('ALLOWED_HOSTS').split(','):
    ALLOWED_HOSTS.append(host)
    CSRF_TRUSTED_ORIGINS.append('https://' + host)
    CSRF_TRUSTED_ORIGINS.append('http://' + host)
    CSRF_TRUSTED_ORIGINS.append('https://www.' + host)
    CSRF_TRUSTED_ORIGINS.append('http://www.' + host)

# Application definition


INSTALLED_APPS = [
    'MasterConfiguration.apps.MasterconfigurationConfig',
    'Account.apps.AccountConfig',
    'MassAlterations.apps.MassalterationsConfig',
    'Reports.apps.ReportsConfig',
    'Staff.apps.AppraiseeConfig',
    'Faculty.FacultyFOET.apps.FacultyfoetConfig',
    'Faculty.FacultySLS.apps.FacultyslsConfig',
    'Faculty.FacultySoEM.apps.FacultysoemConfig',
    'Faculty.FacultyScience.apps.FacultyscienceConfig',
    'Faculty.FacultyMaths.apps.FacultymathsConfig',
    'BulkUpload.BulkUploadFoET.apps.BulkuploadfoetConfig',
    'BulkUpload.BulkUploadFoLS.apps.BulkuploadfolsConfig',
    'BulkUpload.BulkUploadFoEM.apps.BulkuploadfoemConfig',
    'BulkUpload.BulkUploadScience.apps.BulkuploadscienceConfig',
    'BulkUpload.BulkUploadMaths.apps.BulkuploadmathsConfig',
    'HR.apps.HrConfig',
    'RO1.apps.Ro1Config',
    'RO2.apps.Ro2Config',
    'Log.apps.LogConfig',
    'colorfield',
    'admin_interface',
    'mathfilters',
    # 'rest_framework.authtoken',
    "rest_framework",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.home',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_auto_logout.middleware.auto_logout',
    'APAS.middleware.ModelInstance.BaseMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

ROOT_URLCONF = 'APAS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client',
            ],
        },
    },
]

WSGI_APPLICATION = 'APAS.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'Account.User'

X_FRAME_OPTIONS = "SAMEORIGIN"
SILENCED_SYSTEM_CHECKS = ["security.W019"]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

AUTO_LOGOUT = {
    'IDLE_TIME': timedelta(minutes=360),
    'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
}

CSRF_COOKIE_HTTPONLY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# SMTP Configuration
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.pdpu.ac.in'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'noreply.apas@pdpu.ac.in'
EMAIL_HOST_PASSWORD = 'APAS$12#45'
