# Generated by Django 4.1.6 on 2023-03-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyScience', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scienceassistantprofappraisalfile',
            options={'verbose_name': 'Science Assistant Professor Appraisal File', 'verbose_name_plural': 'Science Assistant Professor Appraisal Files'},
        ),
        migrations.AlterModelOptions(
            name='scienceassistantprofoncontractappraisalfile',
            options={'verbose_name': 'Science Assistant Professor On Contract Appraisal File', 'verbose_name_plural': 'Science Assistant Professor On Contract Appraisal Files'},
        ),
        migrations.AlterModelOptions(
            name='scienceassociateprofappraisalfile',
            options={'verbose_name': 'Science Associate Professor Appraisal File', 'verbose_name_plural': 'Science Associate Professor Appraisal Files'},
        ),
        migrations.AlterModelOptions(
            name='sciencegoalsheetassistantprof',
            options={'verbose_name': 'Goalsheet Configuration for Science Assistant Professor', 'verbose_name_plural': 'Goalsheet Configurations for Science Assistant Professor'},
        ),
        migrations.AlterModelOptions(
            name='sciencegoalsheetassistantprofoncontract',
            options={'verbose_name': 'Goalsheet Configuration for Science Assistant Professor On Contract', 'verbose_name_plural': 'Goalsheet Configurations for Science Assistant Professor On Contract'},
        ),
        migrations.AlterModelOptions(
            name='sciencegoalsheetassociateprof',
            options={'verbose_name': 'Goalsheet Configuration for Science Associate Professor', 'verbose_name_plural': 'Goalsheet Configurations for Science Associate Professor'},
        ),
        migrations.AlterModelOptions(
            name='sciencegoalsheetprof',
            options={'verbose_name': 'Goalsheet Configuration for Science Professor On Contract', 'verbose_name_plural': 'Goalsheet Configurations for Science Professor On Contract'},
        ),
        migrations.AlterModelOptions(
            name='scienceprofappraisalfile',
            options={'verbose_name': 'Science Professor Appraisal File', 'verbose_name_plural': 'Science Professor Appraisal Files'},
        ),
    ]
