# Generated by Django 4.1.6 on 2023-03-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyScience', '0002_alter_scienceassistantprofappraisalfile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyvalidator',
            name='consultancy_validated',
        ),
        migrations.RemoveField(
            model_name='facultyvalidator',
            name='dissertation_validated',
        ),
    ]
