# Generated by Django 4.1.6 on 2023-04-09 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyScience', '0004_alter_markfield_ro1_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceassistantprofappraisalfile',
            name='faculty_advisor_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scienceassistantprofappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scienceassociateprofappraisalfile',
            name='faculty_advisor_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scienceassociateprofappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scienceprofappraisalfile',
            name='faculty_advisor_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scienceprofappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=False),
        ),
    ]
