# Generated by Django 4.1.5 on 2023-06-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultyScience', '0009_scienceassistantprofappraisalfile_r1_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scienceassistantprofappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scienceassistantprofappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scienceassistantprofappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scienceassistantprofoncontractappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scienceassistantprofoncontractappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scienceassistantprofoncontractappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scienceassociateprofappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scienceassociateprofappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scienceassociateprofappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scienceprofappraisalfile',
            name='additional_responsibilities_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scienceprofappraisalfile',
            name='self_development_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='scienceprofappraisalfile',
            name='senior_feedback_grade_r2',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding'), ('G', 'Good'), ('A', 'Average'), ('U', 'Unsatisfactory')], max_length=1, null=True),
        ),
    ]
