# Generated by Django 4.1.6 on 2023-03-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySLS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='arranging_conferences',
            field=models.ManyToManyField(blank=True, related_name='sls_arranging_conferences', to='FacultySLS.genericmarkedparameter'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='attending_conferences',
            field=models.ManyToManyField(blank=True, related_name='sls_attending_conferences', to='FacultySLS.genericmarkedparameter'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='bachelors_dissertation',
            field=models.ManyToManyField(blank=True, related_name='sls_bachelors_dissertation', to='FacultySLS.bachelorsdissertation'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='being_mentor',
            field=models.ManyToManyField(blank=True, related_name='sls_being_mentor', to='FacultySLS.genericmarkedparameter'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='community_development',
            field=models.ManyToManyField(blank=True, related_name='sls_community_development', to='FacultySLS.genericmarkedparameter'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='conference_proceedings_scopus_wos',
            field=models.ManyToManyField(blank=True, related_name='sls_conference_proceedings_scopus_wos', to='FacultySLS.paper'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='e_publications_articles',
            field=models.ManyToManyField(blank=True, related_name='sls_e_publications_articles', to='FacultySLS.paper'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='faculty_advisor',
            field=models.ManyToManyField(blank=True, related_name='sls_faculty_advisor', to='FacultySLS.facultyadvisor'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='industry_collaboration',
            field=models.ManyToManyField(blank=True, related_name='sls_industry_collaboration', to='FacultySLS.collaboration'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='literary_books',
            field=models.ManyToManyField(blank=True, related_name='sls_literary_books', to='FacultySLS.publication'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='masters_thesis',
            field=models.ManyToManyField(blank=True, related_name='sls_masters_thesis', to='FacultySLS.mastersdissertation'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='patents',
            field=models.ManyToManyField(blank=True, related_name='sls_patents', to='FacultySLS.patent'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='phd_guidance',
            field=models.ManyToManyField(blank=True, related_name='sls_phd_guidance', to='FacultySLS.phdguidance'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='sls_projects', to='FacultySLS.project'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='providing_consultancy',
            field=models.ManyToManyField(blank=True, related_name='sls_providing_consultancy', to='FacultySLS.consultancy'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='publications_in_scopus_wos',
            field=models.ManyToManyField(blank=True, related_name='sls_publications_in_scopus_wos', to='FacultySLS.paper'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='recognition_awards',
            field=models.ManyToManyField(blank=True, related_name='sls_recognition_awards', to='FacultySLS.award'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='research_books',
            field=models.ManyToManyField(blank=True, related_name='sls_research_books', to='FacultySLS.publication'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='self_development_trainings',
            field=models.ManyToManyField(blank=True, related_name='sls_self_development_trainings', to='FacultySLS.certification'),
        ),
        migrations.AlterField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='textbooks',
            field=models.ManyToManyField(blank=True, related_name='sls_textbook', to='FacultySLS.publication'),
        ),
    ]
