# Generated by Django 4.1.6 on 2023-03-20 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySLS', '0003_folsgoalsheetassistantprof_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folsgoalsheetassistantprof',
            options={'verbose_name': 'Goalsheet Configuration for FoLS Assistant Professor', 'verbose_name_plural': 'Goalsheet Configurations for FoLS Assistant Professor'},
        ),
        migrations.AlterModelOptions(
            name='folsgoalsheetassociateprof',
            options={'verbose_name': 'Goalsheet Configuration for FoLS Associate Professor', 'verbose_name_plural': 'Goalsheet Configurations for FoLS Associate Professor'},
        ),
        migrations.AlterModelOptions(
            name='folsgoalsheetprof',
            options={'verbose_name': 'Goalsheet Configuration for FoLS Professor', 'verbose_name_plural': 'Goalsheet Configurations for FoLS Professor'},
        ),
    ]
