# Generated by Django 4.1.6 on 2023-03-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySLS', '0004_alter_folsgoalsheetassistantprof_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folsassistantprofoncontractappraisalfile',
            options={'verbose_name': 'Science Assistant Professor On Contract Appraisal File', 'verbose_name_plural': 'Science Assistant Professor On Contract Appraisal Files'},
        ),
    ]
