# Generated by Django 4.1.6 on 2023-03-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySLS', '0005_alter_folsassistantprofoncontractappraisalfile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyvalidator',
            name='patents_validated',
        ),
    ]
