# Generated by Django 4.1.6 on 2023-04-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySLS', '0007_alter_markfield_ro1_agreed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folsassistantprofoncontractappraisalfile',
            options={'verbose_name': 'FoLS Assistant Professor On Contract Appraisal File', 'verbose_name_plural': 'FoLS Assistant Professor On Contract Appraisal Files'},
        ),
    ]
