# Generated by Django 4.1.5 on 2023-05-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySLS', '0009_facultyvalidator_academia_collab_validated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folsassistantprofappraisalfile',
            name='r1_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='folsassistantprofappraisalfile',
            name='r1_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folsassistantprofappraisalfile',
            name='r2_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='folsassistantprofappraisalfile',
            name='r2_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='r1_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='r1_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='r2_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='folsassistantprofoncontractappraisalfile',
            name='r2_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folsassociateprofappraisalfile',
            name='r1_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='folsassociateprofappraisalfile',
            name='r1_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folsassociateprofappraisalfile',
            name='r2_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='folsassociateprofappraisalfile',
            name='r2_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folsprofappraisalfile',
            name='r1_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='folsprofappraisalfile',
            name='r1_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folsprofappraisalfile',
            name='r2_grade',
            field=models.CharField(blank=True, choices=[('OUTSTANDING', 'OUTSTANDING'), ('GOOD', 'GOOD'), ('AVERAGE', 'AVERAGE'), ('BELOW AVERAGE', 'BELOW AVERAGE')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='folsprofappraisalfile',
            name='r2_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
