from .views import *
from django.urls import path

urlpatterns = [
    # ro1 Staff Review URL Patterns
    path('staff/<int:pk>/review/', RO1StaffView.staff_review, name='staff_review'),
    path('staff/<int:pk>/review/approve-parameters/', RO1StaffView.approve_parameters, name='approve_params'),
    path('staff/<int:pk>/review/approve-parameters/save/', RO1StaffView.approve_parameters, name='approve_params_save'),
    path('staff/<int:pk>/review/grade-parameters/', RO1StaffView.grade_parameters, name='grade_params'),
    path('staff/<int:pk>/review/grade-parameters/save/', RO1StaffView.grade_parameters, name='grade_params_save'),
    path('staff/<int:pk>/review/grade-self-development/', RO1StaffView.grade_self_development,
         name='grade_self_development'),
    path('staff/<int:pk>/review/grade-self-development/save/', RO1StaffView.grade_self_development,
         name='grade_self_development_save'),
    path('staff/<int:pk>/review/grade-other-activities/', RO1StaffView.grade_other_activities,
         name='grade_other_activities'),
    path('staff/<int:pk>/review/grade-other-activities/save/', RO1StaffView.grade_other_activities,
         name='grade_other_activities_save'),
    path('staff/<int:pk>/review/review-self-evaluation/', RO1StaffView.review_self_evaluation,
         name='review_self_evaluation'),
    path('staff/<int:pk>/review/grade-mooc/', RO1StaffView.grade_mooc, name='grade_mooc'),
    path('staff/<int:pk>/review/grade-mooc/save/', RO1StaffView.grade_mooc, name='grade_mooc_save'),
    path('staff/<int:pk>/review/grade-section-2/', RO1StaffView.grade_section_2, name='grade_section_2'),
    path('staff/<int:pk>/review/grade-section-2/save/', RO1StaffView.grade_section_2, name='grade_section_2save'),
    path('staff/<int:pk>/review/staff-review-all/', RO1StaffView.staff_review_all, name='staff_review_all'),
    path('staff/<int:pk>/review/staff-review-save/', RO1StaffView.staff_review_all_save, name='staff_review_all_save'),
    path('staff/<int:pk>/review/staff-final-submit/', RO1StaffView.staff_final_submit, name='staff_final_submit'),
    path('staff/<int:pk>/review/staff-final-submit/save/', RO1StaffView.staff_final_submit,
         name='staff_final_submit_save'),

    # Base redirect engine
    path('faculty/<int:pk>/review/', RO1FacultyRedirectViewSet.redirect, name='r1-faculty-redirect'),

    # Faculty FOET URL Patterns
    path('faculty/foet/<int:pk>/', RO1FacultyFOETViewSet.dashboard, name='ro1-faculty-foet-faculty-home'),
    path('faculty/foet/<int:pk>/verify/', RO1FacultyFOETViewSet.verify_data, name='ro1-faculty-foet-verify-data'),
    path('faculty/foet/<int:pk>/teaching/', RO1FacultyFOETViewSet.teaching_entry,
         name='ro1-faculty-foet-teaching-entry'),
    path('faculty/foet/<int:pk>/research/', RO1FacultyFOETViewSet.research_entry,
         name='ro1-faculty-foet-research-entry'),
    path('faculty/foet/<int:pk>/project/', RO1FacultyFOETViewSet.project_entry, name='ro1-faculty-foet-project-entry'),
    path('faculty/foet/<int:pk>/phd-guidance/', RO1FacultyFOETViewSet.phd_guidance_entry,
         name='ro1-faculty-foet-phd-guidance-entry'),
    path('faculty/foet/<int:pk>/dissertation/', RO1FacultyFOETViewSet.dissertation_entry,
         name='ro1-faculty-foet-dissertation-entry'),
    path('faculty/foet/<int:pk>/patent/', RO1FacultyFOETViewSet.patent_entry, name='ro1-faculty-foet-patent-entry'),
    path('faculty/foet/<int:pk>/award/', RO1FacultyFOETViewSet.award_entry, name='ro1-faculty-foet-award-entry'),
    path('faculty/foet/<int:pk>/consultancy/', RO1FacultyFOETViewSet.consultancy_entry,
         name='ro1-faculty-foet-consultancy-entry'),
    path('faculty/foet/<int:pk>/academia-collab/', RO1FacultyFOETViewSet.academia_collab_entry,
         name='ro1-faculty-foet-academia-collab-entry'),
    path('faculty/foet/<int:pk>/arranging-conference/', RO1FacultyFOETViewSet.arranging_conference_entry,
         name='ro1-faculty-foet-arranging-conference-entry'),
    path('faculty/foet/<int:pk>/mentorship/', RO1FacultyFOETViewSet.mentorship_entry,
         name='ro1-faculty-foet-mentorship-entry'),
    path('faculty/foet/<int:pk>/attending-conference/', RO1FacultyFOETViewSet.attending_conference_entry,
         name='ro1-faculty-foet-attending-conference-entry'),
    path('faculty/foet/<int:pk>/community-development/', RO1FacultyFOETViewSet.community_development_entry,
         name='ro1-faculty-foet-community-development-entry'),
    path('faculty/foet/<int:pk>/extra-curricular/', RO1FacultyFOETViewSet.extra_curricular_entry,
         name='ro1-faculty-foet-extra-curricular-entry'),
    path('faculty/foet/<int:pk>/additional/', RO1FacultyFOETViewSet.additional_entry,
         name='ro1-faculty-foet-additional-entry'),
    path('faculty/foet/<int:pk>/senior-feedback/', RO1FacultyFOETViewSet.senior_feedback,
         name='ro1-faculty-senior-feedback-entry'),
    path('faculty/foet/<int:pk>/review/', RO1FacultyFOETViewSet.review, name='ro1-faculty-foet-review-entry'),
    path('faculty/foet/<int:pk>/submit/', RO1FacultyFOETViewSet.submit, name='ro1-faculty-foet-submit-entry'),
    path('faculty/foet/<int:pk>/print/', RO1FacultyFOETViewSet.print, name='ro1-faculty-foet-print-entry'),

    # Faculty FOLS URL Patterns
    path('faculty/fols/<int:pk>/', RO1FacultyFOLSViewSet.dashboard, name='ro1-faculty-fols-faculty-home'),
    path('faculty/fols/<int:pk>/verify/', RO1FacultyFOLSViewSet.verify_data, name='ro1-faculty-fols-verify-data'),
    path('faculty/fols/<int:pk>/teaching/', RO1FacultyFOLSViewSet.teaching_entry,
         name='ro1-faculty-fols-teaching-entry'),
    path('faculty/fols/<int:pk>/research/', RO1FacultyFOLSViewSet.research_entry,
         name='ro1-faculty-fols-research-entry'),
    path('faculty/fols/<int:pk>/project/', RO1FacultyFOLSViewSet.project_entry, name='ro1-faculty-fols-project-entry'),
    path('faculty/fols/<int:pk>/phd-guidance/', RO1FacultyFOLSViewSet.phd_guidance_entry,
         name='ro1-faculty-fols-phd-guidance-entry'),
    path('faculty/fols/<int:pk>/dissertation/', RO1FacultyFOLSViewSet.dissertation_entry,
         name='ro1-faculty-fols-dissertation-entry'),
    path('faculty/fols/<int:pk>/patent/', RO1FacultyFOLSViewSet.patent_entry, name='ro1-faculty-fols-patent-entry'),
    path('faculty/fols/<int:pk>/award/', RO1FacultyFOLSViewSet.award_entry, name='ro1-faculty-fols-award-entry'),
    path('faculty/fols/<int:pk>/consultancy/', RO1FacultyFOLSViewSet.consultancy_entry,
         name='ro1-faculty-fols-consultancy-entry'),
    path('faculty/fols/<int:pk>/international-admission/', RO1FacultyFOLSViewSet.international_admission_entry,
         name='ro1-faculty-fols-international-admission-entry'),
    path('faculty/fols/<int:pk>/academia-collab/', RO1FacultyFOLSViewSet.academia_collab_entry,
         name='ro1-faculty-fols-academia-collab-entry'),
    path('faculty/fols/<int:pk>/arranging-conference/', RO1FacultyFOLSViewSet.arranging_conference_entry,
         name='ro1-faculty-fols-arranging-conference-entry'),
    path('faculty/fols/<int:pk>/mentorship/', RO1FacultyFOLSViewSet.mentorship_entry,
         name='ro1-faculty-fols-mentorship-entry'),
    path('faculty/fols/<int:pk>/attending-conference/', RO1FacultyFOLSViewSet.attending_conference_entry,
         name='ro1-faculty-fols-attending-conference-entry'),
    path('faculty/fols/<int:pk>/community-development/', RO1FacultyFOLSViewSet.community_development_entry,
         name='ro1-faculty-fols-community-development-entry'),
    path('faculty/fols/<int:pk>/extra-curricular/', RO1FacultyFOLSViewSet.extra_curricular_entry,
         name='ro1-faculty-fols-extra-curricular-entry'),
    path('faculty/fols/<int:pk>/additional/', RO1FacultyFOLSViewSet.additional_entry,
         name='ro1-faculty-fols-additional-entry'),
    path('faculty/fols/<int:pk>/senior-feedback/', RO1FacultyFOLSViewSet.senior_feedback,
         name='ro1-faculty-senior-feedback-entry'),
    path('faculty/fols/<int:pk>/review/', RO1FacultyFOLSViewSet.review, name='ro1-faculty-fols-review-entry'),
    path('faculty/fols/<int:pk>/submit/', RO1FacultyFOLSViewSet.submit, name='ro1-faculty-fols-submit-entry'),
    path('faculty/fols/<int:pk>/print/', RO1FacultyFOLSViewSet.print, name='ro1-faculty-fols-print-entry'),

    # Faculty FOEM URL Patterns
    path('faculty/foem/<int:pk>/', RO1FacultyFOEMViewSet.dashboard, name='ro1-faculty-foem-faculty-home'),
    path('faculty/foem/<int:pk>/verify/', RO1FacultyFOEMViewSet.verify_data, name='ro1-faculty-foem-verify-data'),
    path('faculty/foem/<int:pk>/teaching/', RO1FacultyFOEMViewSet.teaching_entry,
         name='ro1-faculty-foem-teaching-entry'),
    path('faculty/foem/<int:pk>/research/', RO1FacultyFOEMViewSet.research_entry,
         name='ro1-faculty-foem-research-entry'),
    path('faculty/foem/<int:pk>/project/', RO1FacultyFOEMViewSet.project_entry, name='ro1-faculty-foem-project-entry'),
    path('faculty/foem/<int:pk>/phd-guidance/', RO1FacultyFOEMViewSet.phd_guidance_entry,
         name='ro1-faculty-foem-phd-guidance-entry'),
    path('faculty/foem/<int:pk>/dissertation/', RO1FacultyFOEMViewSet.dissertation_entry,
         name='ro1-faculty-foem-dissertation-entry'),
    path('faculty/foem/<int:pk>/patent/', RO1FacultyFOEMViewSet.patent_entry, name='ro1-faculty-foem-patent-entry'),
    path('faculty/foem/<int:pk>/award/', RO1FacultyFOEMViewSet.award_entry, name='ro1-faculty-foem-award-entry'),
    path('faculty/foem/<int:pk>/consultancy/', RO1FacultyFOEMViewSet.consultancy_entry,
         name='ro1-faculty-foem-consultancy-entry'),
    path('faculty/foem/<int:pk>/academia-collab/', RO1FacultyFOEMViewSet.academia_collab_entry,
         name='ro1-faculty-foem-academia-collab-entry'),
    path('faculty/foem/<int:pk>/arranging-conference/', RO1FacultyFOEMViewSet.arranging_conference_entry,
         name='ro1-faculty-foem-arranging-conference-entry'),
    path('faculty/foem/<int:pk>/mentorship/', RO1FacultyFOEMViewSet.mentorship_entry,
         name='ro1-faculty-foem-mentorship-entry'),
    path('faculty/foem/<int:pk>/attending-conference/', RO1FacultyFOEMViewSet.attending_conference_entry,
         name='ro1-faculty-foem-attending-conference-entry'),
    path('faculty/foem/<int:pk>/community-development/', RO1FacultyFOEMViewSet.community_development_entry,
         name='ro1-faculty-foem-community-development-entry'),
    path('faculty/foem/<int:pk>/extra-curricular/', RO1FacultyFOEMViewSet.extra_curricular_entry,
         name='ro1-faculty-foem-extra-curricular-entry'),
    path('faculty/foem/<int:pk>/additional/', RO1FacultyFOEMViewSet.additional_entry,
         name='ro1-faculty-foem-additional-entry'),
    path('faculty/foem/<int:pk>/senior-feedback/', RO1FacultyFOEMViewSet.senior_feedback,
         name='ro1-faculty-senior-feedback-entry'),
    path('faculty/foem/<int:pk>/review/', RO1FacultyFOEMViewSet.review, name='ro1-faculty-foem-review-entry'),
    path('faculty/foem/<int:pk>/submit/', RO1FacultyFOEMViewSet.submit, name='ro1-faculty-foem-submit-entry'),
    path('faculty/foem/<int:pk>/print/', RO1FacultyFOEMViewSet.print, name='ro1-faculty-foem-print-entry'),

    # Faculty MATHS URL Patterns
    path('faculty/maths/<int:pk>/', RO1FacultyMathViewSet.dashboard, name='ro1-faculty-maths-faculty-home'),
    path('faculty/maths/<int:pk>/verify/', RO1FacultyMathViewSet.verify_data, name='ro1-faculty-maths-verify-data'),
    path('faculty/maths/<int:pk>/teaching/', RO1FacultyMathViewSet.teaching_entry,
         name='ro1-faculty-maths-teaching-entry'),
    path('faculty/maths/<int:pk>/research/', RO1FacultyMathViewSet.research_entry,
         name='ro1-faculty-maths-research-entry'),
    path('faculty/maths/<int:pk>/project/', RO1FacultyMathViewSet.project_entry,
         name='ro1-faculty-maths-project-entry'),
    path('faculty/maths/<int:pk>/phd-guidance/', RO1FacultyMathViewSet.phd_guidance_entry,
         name='ro1-faculty-maths-phd-guidance-entry'),
    path('faculty/maths/<int:pk>/award/', RO1FacultyMathViewSet.award_entry, name='ro1-faculty-maths-award-entry'),
    path('faculty/maths/<int:pk>/academia-collab/', RO1FacultyMathViewSet.academia_collab_entry,
         name='ro1-faculty-maths-academia-collab-entry'),
    path('faculty/maths/<int:pk>/arranging-conference/', RO1FacultyMathViewSet.arranging_conference_entry,
         name='ro1-faculty-maths-arranging-conference-entry'),
    path('faculty/maths/<int:pk>/mentorship/', RO1FacultyMathViewSet.mentorship_entry,
         name='ro1-faculty-maths-mentorship-entry'),
    path('faculty/maths/<int:pk>/attending-conference/', RO1FacultyMathViewSet.attending_conference_entry,
         name='ro1-faculty-maths-attending-conference-entry'),
    path('faculty/maths/<int:pk>/community-development/', RO1FacultyMathViewSet.community_development_entry,
         name='ro1-faculty-maths-community-development-entry'),
    path('faculty/maths/<int:pk>/extra-curricular/', RO1FacultyMathViewSet.extra_curricular_entry,
         name='ro1-faculty-maths-extra-curricular-entry'),
    path('faculty/maths/<int:pk>/additional/', RO1FacultyMathViewSet.additional_entry,
         name='ro1-faculty-maths-additional-entry'),
    path('faculty/maths/<int:pk>/senior-feedback/', RO1FacultyMathViewSet.senior_feedback,
         name='ro1-faculty-senior-feedback-entry'),
    path('faculty/maths/<int:pk>/review/', RO1FacultyMathViewSet.review, name='ro1-faculty-maths-review-entry'),
    path('faculty/maths/<int:pk>/submit/', RO1FacultyMathViewSet.submit, name='ro1-faculty-maths-submit-entry'),
    path('faculty/maths/<int:pk>/print/', RO1FacultyMathViewSet.print, name='ro1-faculty-maths-print-entry'),

    # Faculty SCIENCE URL Patterns
    path('faculty/science/<int:pk>/', RO1FacultyScienceViewSet.dashboard, name='ro1-faculty-science-faculty-home'),
    path('faculty/science/<int:pk>/verify/', RO1FacultyScienceViewSet.verify_data,
         name='ro1-faculty-science-verify-data'),
    path('faculty/science/<int:pk>/teaching/', RO1FacultyScienceViewSet.teaching_entry,
         name='ro1-faculty-science-teaching-entry'),
    path('faculty/science/<int:pk>/research/', RO1FacultyScienceViewSet.research_entry,
         name='ro1-faculty-science-research-entry'),
    path('faculty/science/<int:pk>/project/', RO1FacultyScienceViewSet.project_entry,
         name='ro1-faculty-science-project-entry'),
    path('faculty/science/<int:pk>/phd-guidance/', RO1FacultyScienceViewSet.phd_guidance_entry,
         name='ro1-faculty-science-phd-guidance-entry'),
    path('faculty/science/<int:pk>/dissertation/', RO1FacultyScienceViewSet.dissertation_entry,
         name='ro1-faculty-science-dissertation-entry'),
    path('faculty/science/<int:pk>/patent/', RO1FacultyScienceViewSet.patent_entry,
         name='ro1-faculty-science-patent-entry'),
    path('faculty/science/<int:pk>/award/', RO1FacultyScienceViewSet.award_entry,
         name='ro1-faculty-science-award-entry'),
    path('faculty/science/<int:pk>/consultancy/', RO1FacultyScienceViewSet.consultancy_entry,
         name='ro1-faculty-science-consultancy-entry'),
    path('faculty/science/<int:pk>/academia-collab/', RO1FacultyScienceViewSet.academia_collab_entry,
         name='ro1-faculty-science-academia-collab-entry'),
    path('faculty/science/<int:pk>/arranging-conference/', RO1FacultyScienceViewSet.arranging_conference_entry,
         name='ro1-faculty-science-arranging-conference-entry'),
    path('faculty/science/<int:pk>/mentorship/', RO1FacultyScienceViewSet.mentorship_entry,
         name='ro1-faculty-science-mentorship-entry'),
    path('faculty/science/<int:pk>/attending-conference/', RO1FacultyScienceViewSet.attending_conference_entry,
         name='ro1-faculty-science-attending-conference-entry'),
    path('faculty/science/<int:pk>/community-development/', RO1FacultyScienceViewSet.community_development_entry,
         name='ro1-faculty-science-community-development-entry'),
    path('faculty/science/<int:pk>/extra-curricular/', RO1FacultyScienceViewSet.extra_curricular_entry,
         name='ro1-faculty-science-extra-curricular-entry'),
    path('faculty/science/<int:pk>/additional/', RO1FacultyScienceViewSet.additional_entry,
         name='ro1-faculty-science-additional-entry'),
    path('faculty/science/<int:pk>/senior-feedback/', RO1FacultyScienceViewSet.senior_feedback,
         name='ro1-faculty-senior-feedback-entry'),
    path('faculty/science/<int:pk>/review/', RO1FacultyScienceViewSet.review, name='ro1-faculty-science-review-entry'),
    path('faculty/science/<int:pk>/submit/', RO1FacultyScienceViewSet.submit, name='ro1-faculty-science-submit-entry'),
    path('faculty/science/<int:pk>/print/', RO1FacultyScienceViewSet.print, name='ro1-faculty-science-print-entry'),

    # ro1 dashboard
    path('dashboard/', RO1MainView.dashboard, name='ro1_dashboard'),
    path('dashboard/review/', RO1MainView.review_main, name='ro1_review_main'),
    path('dashboard/review-faculty/', RO1MainView.review_faculty, name='ro1_review_faculty'),
]
