# Generated by Django 4.1.6 on 2023-03-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySoEM', '0002_alter_foemassistantprofappraisalfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foemgoalsheetassistantprof',
            options={'verbose_name': 'Goalsheet Configuration for FoEM Assistant Professor', 'verbose_name_plural': 'Goalsheet Configurations for FoEM Assistant Professor'},
        ),
        migrations.AlterModelOptions(
            name='foemgoalsheetassociateprof',
            options={'verbose_name': 'Goalsheet Configuration for FoEM Associate Professor', 'verbose_name_plural': 'Goalsheet Configurations for FoEM Associate Professor'},
        ),
        migrations.AlterModelOptions(
            name='foemgoalsheetprof',
            options={'verbose_name': 'Goalsheet Configuration for FoEM Professor', 'verbose_name_plural': 'Goalsheet Configurations for FoEM Professor'},
        ),
    ]
