# Generated by Django 4.1.6 on 2023-03-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySoEM', '0003_alter_foemgoalsheetassistantprof_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='category',
            field=models.CharField(blank=True, choices=[('scopus', 'Scopus'), ('sci', 'Science Citation Index'), ('ugc', 'UGC Care'), ('abdc', 'ABDC'), ('wos', 'Web of Science'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
