# Generated by Django 4.1.6 on 2023-03-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySoEM', '0004_alter_paper_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyvalidator',
            name='patents_validated',
        ),
    ]
