# Generated by Django 4.1.6 on 2023-03-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySoEM', '0005_remove_facultyvalidator_patents_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markfield',
            name='ro1_agreed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='markfield',
            name='ro2_agreed',
            field=models.BooleanField(default=True),
        ),
    ]
