# Generated by Django 4.1.6 on 2023-04-09 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySoEM', '0006_alter_markfield_ro1_agreed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foemassistantprofoncontractappraisalfile',
            name='international_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soem_international_admission', to='FacultySoEM.markfield'),
        ),
        migrations.AlterField(
            model_name='foemassistantprofappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='foemprofappraisalfile',
            name='industry_collaboration_available',
            field=models.BooleanField(default=False),
        ),
    ]
