# Generated by Django 4.1.5 on 2023-05-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FacultySoEM', '0007_foemassistantprofoncontractappraisalfile_international_admission_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foemgoalsheetassistantprof',
            old_name='section_4a_attending_conferences_marks_per_conference',
            new_name='section_4a_arranging_conferences_marks_per_conference',
        ),
        migrations.RenameField(
            model_name='foemgoalsheetassistantprof',
            old_name='section_4a_attending_conferences_max_marks',
            new_name='section_4a_arranging_conferences_max_marks',
        ),
        migrations.RenameField(
            model_name='foemgoalsheetassistantprofoncontract',
            old_name='section_4a_attending_conferences_marks_per_conference',
            new_name='section_4a_arranging_conferences_marks_per_conference',
        ),
        migrations.RenameField(
            model_name='foemgoalsheetassistantprofoncontract',
            old_name='section_4a_attending_conferences_max_marks',
            new_name='section_4a_arranging_conferences_max_marks',
        ),
        migrations.RenameField(
            model_name='foemgoalsheetassociateprof',
            old_name='section_4a_attending_conferences_marks_per_conference',
            new_name='section_4a_arranging_conferences_marks_per_conference',
        ),
        migrations.RenameField(
            model_name='foemgoalsheetassociateprof',
            old_name='section_4a_attending_conferences_max_marks',
            new_name='section_4a_arranging_conferences_max_marks',
        ),
    ]
