# Generated by Django 4.1.6 on 2023-03-19 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template', models.FileField(upload_to='bulkupload/templates')),
            ],
            options={
                'verbose_name': 'Download Template',
                'verbose_name_plural': 'Download Template',
            },
        ),
        migrations.CreateModel(
            name='UploadCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('additional', 'Additional Marks (Placement & Admission'), ('co_curricular', 'Co-Curricular Activities'), ('academia_collab', 'Academia Collaboration'), ('consultancy', 'Providing Consultancy'), ('award', 'Awards'), ('phd_guidance', 'PhD Guidance'), ('project', 'Project'), ('scopus_wos_ugc_abdc', 'Paper Publications in Scopus, Web of Science, UGC Care and ABDC'), ('books', 'Books and Publications'), ('exam_duty', 'Exam Duty'), ('student_feedback', 'Student Feedback'), ('teaching_load', 'Teaching Load')], max_length=100)),
                ('file', models.FileField(upload_to='csv_files')),
            ],
            options={
                'verbose_name': 'Upload CSV',
                'verbose_name_plural': 'Upload CSV',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ViewTeachingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('load_odd', models.IntegerField()),
                ('load_even', models.IntegerField()),
                ('load_tri', models.IntegerField(blank=True, null=True)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_teaching_load_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_teaching_load_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Teaching Load',
                'verbose_name_plural': 'View Teaching Loads',
            },
        ),
        migrations.CreateModel(
            name='ViewStudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('student_feedback', models.FloatField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_student_feedback_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_student_feedback_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Student Feedback',
                'verbose_name_plural': 'View Student Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='ViewScopusWos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('entity_name', models.TextField()),
                ('paper_quality', models.CharField(max_length=5)),
                ('isbn', models.CharField(max_length=100)),
                ('conference_organization', models.CharField(max_length=100)),
                ('conference_level', models.CharField(max_length=100)),
                ('is_main_author', models.BooleanField(default=False)),
                ('co_author_count', models.IntegerField()),
                ('is_scopus', models.BooleanField(default=False)),
                ('is_wos', models.BooleanField(default=False)),
                ('is_ugc', models.BooleanField(default=False)),
                ('is_abdc', models.BooleanField(default=False)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_scopus_wos_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_scopus_wos_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Publication in Scopus/WOS',
                'verbose_name_plural': 'View Publications in Scopus/WOS',
            },
        ),
        migrations.CreateModel(
            name='ViewProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('funding_agency', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('role', models.CharField(choices=[('pi', 'PI'), ('copi', 'CO-PI')], max_length=4)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('is_institutional', models.BooleanField(default=False)),
                ('institutional_marks', models.FloatField(default=0)),
                ('is_osrp', models.BooleanField(default=False)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_project_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_project_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Project',
                'verbose_name_plural': 'View Projects',
            },
        ),
        migrations.CreateModel(
            name='ViewPhDGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_phd_guidance_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_phd_guidance_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View PhD Guidance',
                'verbose_name_plural': 'View PhD Guidance',
            },
        ),
        migrations.CreateModel(
            name='ViewPatent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('application_no', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_patent_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_patent_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Patent',
                'verbose_name_plural': 'View Patents',
            },
        ),
        migrations.CreateModel(
            name='ViewExamDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('timely_invigilation', models.FloatField()),
                ('paper_setting', models.FloatField()),
                ('evaluation', models.FloatField()),
                ('result_submission', models.FloatField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_exam_duty_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_exam_duty_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Exam Duty',
                'verbose_name_plural': 'View Exam Duties',
            },
        ),
        migrations.CreateModel(
            name='ViewConsultancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_consultancy_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_consultancy_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Consultancy Provided',
                'verbose_name_plural': 'View Consultancies Provided',
            },
        ),
        migrations.CreateModel(
            name='ViewCoCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('marks', models.FloatField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_co_curricular_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_co_curricular_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Co-Curricular & Extra-Curricular Activities',
                'verbose_name_plural': 'View Co-Curricular & Extra-Curricular Activities',
            },
        ),
        migrations.CreateModel(
            name='ViewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('level', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('text', 'Textbook'), ('research', 'Research Book'), ('literary', 'Literary Book')], max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('is_main_author', models.BooleanField(default=False)),
                ('co_author_count', models.IntegerField()),
                ('is_editor', models.BooleanField(default=False)),
                ('isbn', models.CharField(max_length=100)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_book_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_book_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Book',
                'verbose_name_plural': 'View Books',
            },
        ),
        migrations.CreateModel(
            name='ViewAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('month', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2023)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('level', models.CharField(max_length=20, null=True)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_award_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_award_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Award',
                'verbose_name_plural': 'View Awards',
            },
        ),
        migrations.CreateModel(
            name='ViewAdditionalMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('placement_activity', models.FloatField()),
                ('admission_activity', models.FloatField()),
                ('pgp_chair', models.FloatField()),
                ('e_mba_chair', models.FloatField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_additional_marks_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_additional_marks_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Additional Marks',
                'verbose_name_plural': 'View Additional Marks',
            },
        ),
        migrations.CreateModel(
            name='ViewAcademiaCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('mou_available', models.BooleanField(default=False)),
                ('mou_marks', models.FloatField(default=0)),
                ('marks', models.FloatField()),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_academia_collab_bulk_csv', to='BulkUploadFoEM.uploadcsv')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foem_academia_collab_bulk_faculty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'View Academia Collaboration',
                'verbose_name_plural': 'View Academia Collaboration',
            },
        ),
        migrations.CreateModel(
            name='VerifyUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('csv_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BulkUploadFoEM.uploadcsv')),
            ],
            options={
                'verbose_name': 'Verify Uploaded',
                'verbose_name_plural': 'Verify Uploaded',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_origin', models.FileField(blank=True, null=True, upload_to='error_logs')),
                ('upload_type', models.CharField(blank=True, max_length=100, null=True)),
                ('error', models.TextField()),
                ('type', models.CharField(choices=[('validation', 'Validation'), ('deletion', 'Deletion')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='foem_error_log_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Error Log',
                'verbose_name_plural': 'Error Logs',
            },
        ),
    ]
