from .views import *
from django.urls import path

urlpatterns = [
    # ro2 Staff Review URL Patterns
    path('staff/<int:pk>/review/', RO2StaffView.staff_review, name='r2_staff_review'),
    path('staff/<int:pk>/review/approve-parameters/', RO2StaffView.approve_parameters, name='r2_approve_params'),
    path('staff/<int:pk>/review/approve-parameters/save/', RO2StaffView.approve_parameters, name='r2_approve_params_save'),
    path('staff/<int:pk>/review/grade-parameters/', RO2StaffView.grade_parameters, name='r2_grade_params'),
    path('staff/<int:pk>/review/grade-parameters/save/', RO2StaffView.grade_parameters, name='r2_grade_params_save'),
    path('staff/<int:pk>/review/grade-self-development/', RO2StaffView.grade_self_development, name='r2_grade_self_development'),
    path('staff/<int:pk>/review/grade-self-development/save/', RO2StaffView.grade_self_development, name='r2_grade_self_development_save'),
    path('staff/<int:pk>/review/grade-other-activities/', RO2StaffView.grade_other_activities, name='r2_grade_other_activities'),
    path('staff/<int:pk>/review/grade-other-activities/save/', RO2StaffView.grade_other_activities, name='r2_grade_other_activities_save'),
    path('staff/<int:pk>/review/review-self-evaluation/', RO2StaffView.review_self_evaluation, name='r2_review_self_evaluation'),
    path('staff/<int:pk>/review/grade-mooc/', RO2StaffView.grade_mooc, name='r2_grade_mooc'),
    path('staff/<int:pk>/review/grade-mooc/save/', RO2StaffView.grade_mooc, name='r2_grade_mooc_save'),
    path('staff/<int:pk>/review/grade-section-2/', RO2StaffView.grade_section_2, name='r2_grade_section_2'),
    path('staff/<int:pk>/review/grade-section-2/save/', RO2StaffView.grade_section_2, name='r2_grade_section_2save'),
    path('staff/<int:pk>/review/staff-review-all/', RO2StaffView.staff_review_all, name='r2_staff_review_all'),
    path('staff/<int:pk>/review/staff-review-save/', RO2StaffView.staff_review_save, name='r2_staff_review_save'),
    path('staff/<int:pk>/review/staff-final-submit/', RO2StaffView.staff_final_submit, name='r2_staff_final_submit'),
    path('staff/<int:pk>/review/staff-final-submit/save/', RO2StaffView.staff_final_submit, name='r2_staff_final_submit_save'),

    path('faculty/<int:pk>/review/', RO2FacultyRedirectViewSet.redirect, name='r2-faculty-redirect'),

    path('faculty/foet/<int:pk>/', RO2FacultyFOETViewSet.dashboard, name='ro2-faculty-foet-faculty-home'),
    path('faculty/foet/<int:pk>/verify/', RO2FacultyFOETViewSet.verify_data, name='ro2-faculty-foet-verify-data'),
    path('faculty/foet/<int:pk>/teaching/', RO2FacultyFOETViewSet.teaching_entry, name='ro2-faculty-foet-teaching-entry'),
    path('faculty/foet/<int:pk>/research/', RO2FacultyFOETViewSet.research_entry, name='ro2-faculty-foet-research-entry'),
    path('faculty/foet/<int:pk>/phd-guidance/', RO2FacultyFOETViewSet.phd_guidance_entry, name='ro2-faculty-foet-phd-guidance-entry'),
    path('faculty/foet/<int:pk>/project/', RO2FacultyFOETViewSet.project_entry, name='ro2-faculty-foet-project-entry'),
    path('faculty/foet/<int:pk>/dissertation/', RO2FacultyFOETViewSet.dissertation_entry, name='ro2-faculty-foet-dissertation-entry'),
    path('faculty/foet/<int:pk>/patent/', RO2FacultyFOETViewSet.patent_entry, name='ro2-faculty-foet-patent-entry'),
    path('faculty/foet/<int:pk>/award/', RO2FacultyFOETViewSet.award_entry, name='ro2-faculty-foet-award-entry'),
    path('faculty/foet/<int:pk>/consultancy/', RO2FacultyFOETViewSet.consultancy_entry, name='ro2-faculty-foet-consultancy-entry'),
    path('faculty/foet/<int:pk>/academia-collab/', RO2FacultyFOETViewSet.academia_collab_entry, name='ro2-faculty-foet-academia-collab-entry'),
    path('faculty/foet/<int:pk>/arranging-conference/', RO2FacultyFOETViewSet.arranging_conference_entry, name='ro2-faculty-foet-arranging-conference-entry'),
    path('faculty/foet/<int:pk>/mentorship/', RO2FacultyFOETViewSet.mentorship_entry, name='ro2-faculty-foet-mentorship-entry'),
    path('faculty/foet/<int:pk>/attending-conference/', RO2FacultyFOETViewSet.attending_conference_entry, name='ro2-faculty-foet-attending-conference-entry'),
    path('faculty/foet/<int:pk>/community-development/', RO2FacultyFOETViewSet.community_development_entry, name='ro2-faculty-foet-community-development-entry'),
    path('faculty/foet/<int:pk>/extra-curricular/', RO2FacultyFOETViewSet.extra_curricular_entry, name='ro2-faculty-foet-extra-curricular-entry'),
    path('faculty/foet/<int:pk>/additional/', RO2FacultyFOETViewSet.additional_entry, name='ro2-faculty-foet-additional-entry'),
    path('faculty/foet/<int:pk>/senior-feedback/', RO2FacultyFOETViewSet.senior_feedback, name='ro2-faculty-senior-feedback-entry'),
    path('faculty/foet/<int:pk>/review/', RO2FacultyFOETViewSet.review, name='ro2-faculty-foet-review-entry'),
    path('faculty/foet/<int:pk>/submit/', RO2FacultyFOETViewSet.submit, name='ro2-faculty-foet-submit-entry'),
    path('faculty/foet/<int:pk>/print/', RO2FacultyFOETViewSet.print, name='ro2-faculty-foet-print-entry'),


    # Faculty FOLS URL Patterns
    path('faculty/fols/<int:pk>/', RO2FacultyFOLSViewSet.dashboard, name='ro2-faculty-fols-faculty-home'),
    path('faculty/fols/<int:pk>/verify/', RO2FacultyFOLSViewSet.verify_data, name='ro2-faculty-fols-verify-data'),
    path('faculty/fols/<int:pk>/teaching/', RO2FacultyFOLSViewSet.teaching_entry, name='ro2-faculty-fols-teaching-entry'),
    path('faculty/fols/<int:pk>/research/', RO2FacultyFOLSViewSet.research_entry, name='ro2-faculty-fols-research-entry'),
    path('faculty/fols/<int:pk>/project/', RO2FacultyFOLSViewSet.project_entry, name='ro2-faculty-fols-project-entry'),
    path('faculty/fols/<int:pk>/phd-guidance/', RO2FacultyFOLSViewSet.phd_guidance_entry, name='ro2-faculty-fols-phd-guidance-entry'),
    path('faculty/fols/<int:pk>/dissertation/', RO2FacultyFOLSViewSet.dissertation_entry, name='ro2-faculty-fols-dissertation-entry'),
    path('faculty/fols/<int:pk>/award/', RO2FacultyFOLSViewSet.award_entry, name='ro2-faculty-fols-award-entry'),
    path('faculty/fols/<int:pk>/consultancy/', RO2FacultyFOLSViewSet.consultancy_entry, name='ro2-faculty-fols-consultancy-entry'),
    path('faculty/fols/<int:pk>/international-admission/', RO2FacultyFOLSViewSet.international_admission_entry, name='ro2-faculty-fols-international-admission-entry'),
    path('faculty/fols/<int:pk>/academia-collab/', RO2FacultyFOLSViewSet.academia_collab_entry, name='ro2-faculty-fols-academia-collab-entry'),
    path('faculty/fols/<int:pk>/arranging-conference/', RO2FacultyFOLSViewSet.arranging_conference_entry, name='ro2-faculty-fols-arranging-conference-entry'),
    path('faculty/fols/<int:pk>/mentorship/', RO2FacultyFOLSViewSet.mentorship_entry, name='ro2-faculty-fols-mentorship-entry'),
    path('faculty/fols/<int:pk>/attending-conference/', RO2FacultyFOLSViewSet.attending_conference_entry, name='ro2-faculty-fols-attending-conference-entry'),
    path('faculty/fols/<int:pk>/community-development/', RO2FacultyFOLSViewSet.community_development_entry, name='ro2-faculty-fols-community-development-entry'),
    path('faculty/fols/<int:pk>/extra-curricular/', RO2FacultyFOLSViewSet.extra_curricular_entry, name='ro2-faculty-fols-extra-curricular-entry'),
    path('faculty/fols/<int:pk>/additional/', RO2FacultyFOLSViewSet.additional_entry, name='ro2-faculty-fols-additional-entry'),
    path('faculty/fols/<int:pk>/senior-feedback/', RO2FacultyFOLSViewSet.senior_feedback, name='ro1-faculty-senior-feedback-entry'),
    path('faculty/fols/<int:pk>/review/', RO2FacultyFOLSViewSet.review, name='ro2-faculty-fols-review-entry'),
    path('faculty/fols/<int:pk>/submit/', RO2FacultyFOLSViewSet.submit, name='ro2-faculty-fols-submit-entry'),
    path('faculty/fols/<int:pk>/print/', RO2FacultyFOLSViewSet.print, name='ro2-faculty-fols-print-entry'),
    
    # Faculty FOEM URL Patterns
    path('faculty/foem/<int:pk>/', RO2FacultyFOEMViewSet.dashboard, name='ro2-faculty-foem-faculty-home'),
    path('faculty/foem/<int:pk>/verify/', RO2FacultyFOEMViewSet.verify_data, name='ro2-faculty-foem-verify-data'),
    path('faculty/foem/<int:pk>/teaching/', RO2FacultyFOEMViewSet.teaching_entry, name='ro2-faculty-foem-teaching-entry'),
    path('faculty/foem/<int:pk>/research/', RO2FacultyFOEMViewSet.research_entry, name='ro2-faculty-foem-research-entry'),
    path('faculty/foem/<int:pk>/project/', RO2FacultyFOEMViewSet.project_entry, name='ro2-faculty-foem-project-entry'),
    path('faculty/foem/<int:pk>/phd-guidance/', RO2FacultyFOEMViewSet.phd_guidance_entry, name='ro2-faculty-foem-phd-guidance-entry'),
    path('faculty/foem/<int:pk>/dissertation/', RO2FacultyFOEMViewSet.dissertation_entry, name='ro2-faculty-foem-dissertation-entry'),
    path('faculty/foem/<int:pk>/award/', RO2FacultyFOEMViewSet.award_entry, name='ro2-faculty-foem-award-entry'),
    path('faculty/foem/<int:pk>/consultancy/', RO2FacultyFOEMViewSet.consultancy_entry, name='ro2-faculty-foem-consultancy-entry'),
    path('faculty/foem/<int:pk>/academia-collab/', RO2FacultyFOEMViewSet.academia_collab_entry, name='ro2-faculty-foem-academia-collab-entry'),
    path('faculty/foem/<int:pk>/arranging-conference/', RO2FacultyFOEMViewSet.arranging_conference_entry, name='ro2-faculty-foem-arranging-conference-entry'),
    path('faculty/foem/<int:pk>/mentorship/', RO2FacultyFOEMViewSet.mentorship_entry, name='ro2-faculty-foem-mentorship-entry'),
    path('faculty/foem/<int:pk>/attending-conference/', RO2FacultyFOEMViewSet.attending_conference_entry, name='ro2-faculty-foem-attending-conference-entry'),
    path('faculty/foem/<int:pk>/community-development/', RO2FacultyFOEMViewSet.community_development_entry, name='ro2-faculty-foem-community-development-entry'),
    path('faculty/foem/<int:pk>/extra-curricular/', RO2FacultyFOEMViewSet.extra_curricular_entry, name='ro2-faculty-foem-extra-curricular-entry'),
    path('faculty/foem/<int:pk>/additional/', RO2FacultyFOEMViewSet.additional_entry, name='ro2-faculty-foem-additional-entry'),
    path('faculty/foem/<int:pk>/senior-feedback/', RO2FacultyFOEMViewSet.senior_feedback, name='ro1-faculty-senior-feedback-entry'),
    path('faculty/foem/<int:pk>/review/', RO2FacultyFOEMViewSet.review, name='ro2-faculty-foem-review-entry'),
    path('faculty/foem/<int:pk>/submit/', RO2FacultyFOEMViewSet.submit, name='ro2-faculty-foem-submit-entry'),
    path('faculty/foem/<int:pk>/print/', RO2FacultyFOEMViewSet.print, name='ro2-faculty-foem-print-entry'),

    # Faculty MATHS URL Patterns
    path('faculty/maths/<int:pk>/', RO2FacultyMathViewSet.dashboard, name='ro2-faculty-maths-faculty-home'),
    path('faculty/maths/<int:pk>/verify/', RO2FacultyMathViewSet.verify_data, name='ro2-faculty-maths-verify-data'),
    path('faculty/maths/<int:pk>/teaching/', RO2FacultyMathViewSet.teaching_entry, name='ro2-faculty-maths-teaching-entry'),
    path('faculty/maths/<int:pk>/research/', RO2FacultyMathViewSet.research_entry, name='ro2-faculty-maths-research-entry'),
    path('faculty/maths/<int:pk>/project/', RO2FacultyMathViewSet.project_entry, name='ro2-faculty-maths-project-entry'),
    path('faculty/maths/<int:pk>/phd-guidance/', RO2FacultyMathViewSet.phd_guidance_entry, name='ro2-faculty-maths-phd-guidance-entry'),
    path('faculty/maths/<int:pk>/award/', RO2FacultyMathViewSet.award_entry, name='ro2-faculty-maths-award-entry'),
    path('faculty/maths/<int:pk>/academia-collab/', RO2FacultyMathViewSet.academia_collab_entry, name='ro2-faculty-maths-academia-collab-entry'),
    path('faculty/maths/<int:pk>/arranging-conference/', RO2FacultyMathViewSet.arranging_conference_entry, name='ro2-faculty-maths-arranging-conference-entry'),
    path('faculty/maths/<int:pk>/mentorship/', RO2FacultyMathViewSet.mentorship_entry, name='ro2-faculty-maths-mentorship-entry'),
    path('faculty/maths/<int:pk>/attending-conference/', RO2FacultyMathViewSet.attending_conference_entry, name='ro2-faculty-maths-attending-conference-entry'),
    path('faculty/maths/<int:pk>/community-development/', RO2FacultyMathViewSet.community_development_entry, name='ro2-faculty-maths-community-development-entry'),
    path('faculty/maths/<int:pk>/extra-curricular/', RO2FacultyMathViewSet.extra_curricular_entry, name='ro2-faculty-maths-extra-curricular-entry'),
    path('faculty/maths/<int:pk>/additional/', RO2FacultyMathViewSet.additional_entry, name='ro2-faculty-maths-additional-entry'),
    path('faculty/maths/<int:pk>/senior-feedback/', RO2FacultyMathViewSet.senior_feedback, name='ro1-faculty-senior-feedback-entry'),
    path('faculty/maths/<int:pk>/review/', RO2FacultyMathViewSet.review, name='ro2-faculty-maths-review-entry'),
    path('faculty/maths/<int:pk>/submit/', RO2FacultyMathViewSet.submit, name='ro2-faculty-maths-submit-entry'),
    path('faculty/maths/<int:pk>/print/', RO2FacultyMathViewSet.print, name='ro2-faculty-maths-print-entry'),


    # Faculty SCIENCE URL Patterns
    path('faculty/science/<int:pk>/', RO2FacultyScienceViewSet.dashboard, name='ro2-faculty-science-faculty-home'),
    path('faculty/science/<int:pk>/verify/', RO2FacultyScienceViewSet.verify_data, name='ro2-faculty-science-verify-data'),
    path('faculty/science/<int:pk>/teaching/', RO2FacultyScienceViewSet.teaching_entry, name='ro2-faculty-science-teaching-entry'),
    path('faculty/science/<int:pk>/research/', RO2FacultyScienceViewSet.research_entry, name='ro2-faculty-science-research-entry'),
    path('faculty/science/<int:pk>/phd-guidance/', RO2FacultyScienceViewSet.phd_guidance_entry, name='ro2-faculty-science-phd-guidance-entry'),
    path('faculty/science/<int:pk>/project/', RO2FacultyScienceViewSet.project_entry, name='ro2-faculty-science-project-entry'),
    path('faculty/science/<int:pk>/patent/', RO2FacultyScienceViewSet.patent_entry, name='ro2-faculty-science-patent-entry'),
    path('faculty/science/<int:pk>/award/', RO2FacultyScienceViewSet.award_entry, name='ro2-faculty-science-award-entry'),
    path('faculty/science/<int:pk>/academia-collab/', RO2FacultyScienceViewSet.academia_collab_entry, name='ro2-faculty-science-academia-collab-entry'),
    path('faculty/science/<int:pk>/arranging-conference/', RO2FacultyScienceViewSet.arranging_conference_entry, name='ro2-faculty-science-arranging-conference-entry'),
    path('faculty/science/<int:pk>/mentorship/', RO2FacultyScienceViewSet.mentorship_entry, name='ro2-faculty-science-mentorship-entry'),
    path('faculty/science/<int:pk>/attending-conference/', RO2FacultyScienceViewSet.attending_conference_entry, name='ro2-faculty-science-attending-conference-entry'),
    path('faculty/science/<int:pk>/community-development/', RO2FacultyScienceViewSet.community_development_entry, name='ro2-faculty-science-community-development-entry'),
    path('faculty/science/<int:pk>/extra-curricular/', RO2FacultyScienceViewSet.extra_curricular_entry, name='ro2-faculty-science-extra-curricular-entry'),
    path('faculty/science/<int:pk>/additional/', RO2FacultyScienceViewSet.additional_entry, name='ro2-faculty-science-additional-entry'),
    path('faculty/science/<int:pk>/senior-feedback/', RO2FacultyScienceViewSet.senior_feedback, name='ro2-faculty-senior-feedback-entry'),
    path('faculty/science/<int:pk>/review/', RO2FacultyScienceViewSet.review, name='ro2-faculty-science-review-entry'),
    path('faculty/science/<int:pk>/submit/', RO2FacultyScienceViewSet.submit, name='ro2-faculty-science-submit-entry'),
    path('faculty/science/<int:pk>/print/', RO2FacultyScienceViewSet.print, name='ro2-faculty-science-print-entry'),
    path('faculty/science/<int:pk>/print/', RO2FacultyScienceViewSet.print, name='ro2-faculty-science-print-entry'),



    # ro2 dashboard
    path('dashboard/', RO2MainView.dashboard, name='ro2_dashboard'),
    path('dashboard/review/', RO2MainView.review_main, name='ro2_review_main'),
    path('dashboard/review-faculty/', RO2MainView.review_faculty, name='ro2_review_faculty'),
]
